const rulesIndexExport = {
  "bellowers & musicians": "special-rules/bellowers-and-musicians",
  "ancestral grudge": "special-rules/ancestral-grudge",
  "goad beast": "special-rules/goad-beast",
  "mob rule": "special-rules/mob-rule",
  "arcane shield": "special-rules/arcane-shield",
  "infernal engineer": "special-rules/infernal-engineer",
  "my will be done": "special-rules/my-will-be-done",
  "banished lords": "special-rules/banished-lords",
  "horn of isha": "special-rules/horn-of-isha",
  "aura of the lady": "special-rules/aura-of-the-lady",
  '"grind them down!"': "special-rules/grind-them-down",
  brayhorn: "special-rules/brayhorn",
  "the arrow of kurnous": "special-rules/the-arrow-of-kurnous",
  "rampant mutation": "special-rules/rampant-mutation",
  "eshin infiltration": "special-rules/eshin-infiltration",
  "daemonic charge": "special-rules/daemonic-charge",
  "banner of the count": "special-rules/banner-of-the-count",
  '"hold the line!"': "special-rules/hold-the-line",
  "hidden skaven": "special-rules/hidden-skaven",
  "naval discipline": "special-rules/naval-discipline",
  "shield of the lady": "special-rules/shield-of-the-lady",
  "sorcerer's curse": "special-rules/sorcerers-curse",
  "master of battle": "special-rules/master-of-battle",
  gorefeast: "special-rules/gorefeast",
  "gifts of khaine": "special-rules/gifts-of-khaine",
  "the exile's vow": "special-rules/the-exiles-vow",
  guardians: "special-rules/guardians",
  "troubadour of loec": "special-rules/troubadour-of-loec",
  "ogre charge": "special-rules/ogre-charge",
  "bull charge": "special-rules/bull-charge",
  "the language of the priests": "special-rules/the-language-of-the-priests",
  oathstone: "special-rules/oathstone",
  "banner of the king": "special-rules/banner-of-the-king",
  "slaughterer's call": "special-rules/slaughterers-call",
  "the death of a general": "special-rules/the-death-of-a-general",
  "big stabbas": "special-rules/big-stabbas",
  "chracian warriors": "special-rules/chracian-warriors",
  "borne aloft": "special-rules/borne-aloft",
  "peasant's duty": "special-rules/peasants-duty",
  "hawk-eyed archer": "special-rules/hawk-eyed-archer",
  "reclaimed glory": "special-rules/reclaimed-glory",
  "invocation of nehek": "special-rules/invocation-of-nehek",
  "bestial charge": "special-rules/bestial-charge",
  "skulking menace": "special-rules/skulking-menace",
  "cloud of flies": "special-rules/cloud-of-flies",
  "lay in wait": "special-rules/lay-in-wait",
  "spawn of khorne": "special-rules/spawn-of-khorne",
  "butcher's cauldron": "special-rules/butchers-cauldron",
  "skirmish screen": "special-rules/skirmish-screen",
  "hidden dark elves": "special-rules/hidden-dark-elves",
  "totem of endless bloodletting":
    "special-rules/totem-of-endless-bloodletting",
  "suffer not...": "special-rules/suffer-not",
  "quell panic": "special-rules/quell-panic",
  "sworn protector": "special-rules/sworn-protector",
  "ancestral shield": "special-rules/ancestral-shield",
  "king's guard": "special-rules/kings-guard",
  "spawn of nurgle": "special-rules/spawn-of-nurgle",
  "masterful outriders": "special-rules/masterful-outriders",
  "forbidden poisons": "special-rules/forbidden-poisons",
  "deploying weapon teams": "special-rules/deploying-weapon-teams",
  "crusading knights": "special-rules/crusading-knights",
  "toad rage": "special-rules/toad-rage",
  "storm call": "special-rules/storm-call",
  netters: "special-rules/netters",
  "the hunger": "special-rules/the-hunger",
  "running with the pack": "special-rules/running-with-the-pack",
  "arise!": "special-rules/arise",
  "carriage hauler": "special-rules/carriage-hauler",
  "prayers of sigmar": "special-rules/prayers-of-sigmar",
  "brazen wheels": "special-rules/brazen-wheels",
  "beguiling aura": "special-rules/beguiling-aura",
  "crown of antlers": "special-rules/crown-of-antlers",
  "release the fanatics!": "special-rules/release-the-fanatics",
  "weapon team leadership": "special-rules/weapon-team-leadership",
  "blood frenzy": "special-rules/blood-frenzy",
  "attention seeker": "special-rules/attention-seeker",
  "spawn of slaanesh": "special-rules/spawn-of-slaanesh",
  "martial prowess": "special-rules/martial-prowess",
  "steadfast discipline": "special-rules/steadfast-discipline",
  "dance of death": "special-rules/dance-of-death",
  "prayers of ulric": "special-rules/prayers-of-ulric",
  "wight banner": "special-rules/wight-banner",
  "blessings of the volcano god": "special-rules/blessings-of-the-volcano-god",
  "grail monk": "special-rules/grail-monk",
  "from beneath the sands": "special-rules/from-beneath-the-sands",
  "strike the runes": "special-rules/strike-the-runes",
  "maddening aura": "special-rules/maddening-aura",
  "crusader's zeal": "special-rules/crusaders-zeal",
  "grail reliquae": "special-rules/grail-reliquae",
  "lumbering destruction": "special-rules/lumbering-destruction",
  "spawn of tzeentch": "special-rules/spawn-of-tzeentch",
  "squigs go wild": "special-rules/squigs-go-wild",
  "engine of the gods": "special-rules/engine-of-the-gods",
  "slime trail": "special-rules/slime-trail",
  "clouds of soot & smoke": "special-rules/clouds-of-soot-and-smoke",
  "implacable defence": "special-rules/implacable-defence",
  "targeting weapon teams": "special-rules/targeting-weapon-teams",
  "the hierophant": "special-rules/the-hierophant",
  "spurting bile blood": "special-rules/spurting-bile-blood",
  forgefire: "special-rules/forgefire",
  "deflect shots": "special-rules/deflect-shots",
  "authority of the hierophant": "special-rules/authority-of-the-hierophant",
  "traps & snares": "special-rules/traps-and-snares",
  "cursed coven": "special-rules/cursed-coven",
  "the crusader's vow": "special-rules/the-crusaders-vow",
  "guardians of the wildwood": "special-rules/guardians-of-the-wildwood",
  "bound spirits": "special-rules/bound-spirits",
  "harmonious incantations": "special-rules/harmonious-incantations",
  handler: "special-rules/handler",
  cannonade: "special-rules/cannonade",
  "ravenous hunger": "special-rules/ravenous-hunger",
  "slayer of daemons": "special-rules/slayer-of-daemons",
  "ker-splat": "special-rules/ker-splat",
  "arcane configuration": "special-rules/arcane-configuration",
  "eternal taskmaster": "special-rules/eternal-taskmaster",
  pavise: "special-rules/pavise",
  "earn your spurs": "special-rules/earn-your-spurs",
  "dark runes": "special-rules/dark-runes",
  "stony stare": "special-rules/stony-stare",
  "retinue of the saints": "special-rules/retinue-of-the-saints",
  "scintillating sorcery": "special-rules/scintillating-sorcery",
  "warriors of the white tower": "special-rules/warriors-of-the-white-tower",
  "master of ballistics": "special-rules/master-of-ballistics",
  "dances of loec": "special-rules/dances-of-loec",
  skullcracker: "special-rules/skullcracker",
  "wilful beast": "special-rules/wilful-beast",
  "slayer of dragons": "special-rules/slayer-of-dragons",
  "cloud of dust": "special-rules/cloud-of-dust",
  "aura of the fay": "special-rules/aura-of-the-fay",
  "sepulchral animus": "special-rules/sepulchral-animus",
  "largely insignificant": "special-rules/largely-insignificant",
  "leader of the pack": "special-rules/leader-of-the-pack",
  "witness to destiny": "special-rules/witness-to-destiny",
  "blessings of khaine": "special-rules/blessings-of-khaine",
  "daughters of eternity": "special-rules/daughters-of-eternity",
  "spiked ball & chains": "special-rules/spiked-ball-and-chains",
  ambushers: "special-rules/ambushers",
  "accursed weapons": "special-rules/accursed-weapons",
  "burning alignment": "special-rules/burning-alignment",
  "living saints": "special-rules/living-saints",
  "fanatical zeal": "special-rules/fanatical-zeal",
  ghostsight: "special-rules/ghostsight",
  "slashing attack": "special-rules/slashing-attack",
  "giant attacks": "special-rules/giant-attacks",
  "born of fire": "special-rules/born-of-fire",
  "look-out gnoblar": "special-rules/look-out-gnoblar",
  "two-headed dragon": "special-rules/two-headed-dragon",
  "abyssal howl": "special-rules/abyssal-howl",
  "deepwood coven": "special-rules/deepwood-coven",
  "safe from harm": "special-rules/safe-from-harm",
  "martial pride": "special-rules/martial-pride",
  "feel no pain": "special-rules/feel-no-pain",
  "blessed knight": "special-rules/blessed-knight",
  "dispersed formation": "special-rules/dispersed-formation",
  "warriors of nagarythe": "special-rules/warriors-of-nagarythe",
  "unstoppable assault": "special-rules/unstoppable-assault",
  "armour bane": "special-rules/armour-bane",
  "the terrors below": "special-rules/the-terrors-below",
  "soul-eater": "special-rules/soul-eater",
  "chaos armour daemons of chaos":
    "special-rules/chaos-armour-daemons-of-chaos",
  "impervious defence": "special-rules/impervious-defence",
  "artillery master": "special-rules/artillery-master",
  "guardian of the sacred sites": "special-rules/guardian-of-the-sacred-sites",
  "sons of caledor": "special-rules/sons-of-caledor",
  "swallow whole": "special-rules/swallow-whole",
  "slavering charge": "special-rules/slavering-charge",
  "blessings of the horned rat": "special-rules/blessings-of-the-horned-rat",
  entrenchment: "special-rules/entrenchment",
  "mournfang charge": "special-rules/mournfang-charge",
  "pick up and...": "special-rules/pick-up-and",
  "soul reaper": "special-rules/soul-reaper",
  "ark of sotek": "special-rules/ark-of-sotek",
  "inner circle": "special-rules/inner-circle",
  "eternal hatred": "special-rules/eternal-hatred",
  "elven reflexes": "special-rules/elven-reflexes",
  daemonic: "special-rules/daemonic",
  "blessings of the lady": "special-rules/blessings-of-the-lady",
  "sorcerous miasma": "special-rules/sorcerous-miasma",
  "commander of legions": "special-rules/commander-of-legions",
  "caged fury": "special-rules/caged-fury",
  "armoured hide": "special-rules/armoured-hide",
  "hellcannon misfire table": "special-rules/hellcannon-misfire-table",
  "finest warhorses": "special-rules/finest-warhorses",
  "from the ashes": "special-rules/from-the-ashes",
  "holy fervour": "special-rules/holy-fervour",
  "the wyrm slayer": "special-rules/the-wyrm-slayer",
  "daemonic instability": "special-rules/daemonic-instability",
  "screaming skulls": "special-rules/screaming-skulls",
  "breath weapon": "special-rules/breath-weapon",
  "settra does not kneel!": "special-rules/settra-does-not-kneel",
  "hekarti's blessing": "special-rules/hekartis-blessing",
  "tolling the bell": "special-rules/tolling-the-bell",
  bully: "special-rules/bully",
  "slithering serpents": "special-rules/slithering-serpents",
  "blood greed": "special-rules/blood-greed",
  '"stand back chief"': "special-rules/stand-back-chief",
  "numbing chill": "special-rules/numbing-chill",
  "spectral reapers": "special-rules/spectral-reapers",
  "talismanic tattoos": "special-rules/talismanic-tattoos",
  quake: "special-rules/quake",
  venerable: "special-rules/venerable",
  "blood rage": "special-rules/blood-rage",
  "arcane backlash": "special-rules/arcane-backlash",
  "ghoulish glamour": "special-rules/ghoulish-glamour",
  "chariot runners": "special-rules/chariot-runners",
  "great censer": "special-rules/great-censer",
  "spawn of sotek": "special-rules/spawn-of-sotek",
  murderous: "special-rules/murderous",
  "daemonic locus": "special-rules/daemonic-locus",
  "big 'uns": "special-rules/big-uns",
  "settra the great": "special-rules/settra-the-great",
  "chaos armour warriors of chaos":
    "special-rules/chaos-armour-warriors-of-chaos",
  "slow reload": "special-rules/slow-reload",
  "wake of fire": "special-rules/wake-of-fire",
  "tree spirit": "special-rules/tree-spirit",
  "lance formation": "special-rules/lance-formation",
  "symbol of might": "special-rules/symbol-of-might",
  "skulls of the foe": "special-rules/skulls-of-the-foe",
  peasantry: "special-rules/peasantry",
  "solar engine": "special-rules/solar-engine",
  "witch bane": "special-rules/witch-bane",
  "sea dragon cloak": "special-rules/sea-dragon-cloak",
  "infernal favour": "special-rules/infernal-favour",
  "scarab prince": "special-rules/scarab-prince",
  choppas: "special-rules/choppas",
  "untutored arcanist": "special-rules/untutored-arcanist",
  "close order": "special-rules/close-order",
  "scrying pool": "special-rules/scrying-pool",
  backstab: "special-rules/backstab",
  "blizzard aura": "special-rules/blizzard-aura",
  "covenant of power": "special-rules/covenant-of-power",
  "crushing bulk": "special-rules/crushing-bulk",
  "royal guard": "special-rules/royal-guard",
  "ensorcelled weapons": "special-rules/ensorcelled-weapons",
  "stone skeleton": "special-rules/stone-skeleton",
  "bull-gors": "special-rules/bull-gors",
  "tree whack": "special-rules/tree-whack",
  "immovable object": "special-rules/immovable-object",
  "stoic defenders": "special-rules/stoic-defenders",
  "the knight's vow": "special-rules/the-knights-vow",
  "blackshard armour": "special-rules/blackshard-armour",
  "grinding wheels": "special-rules/grinding-wheels",
  drunken: "special-rules/drunken",
  "da boyz": "special-rules/da-boyz",
  "daemonic alignment": "special-rules/daemonic-alignment",
  "usirian's reaper": "special-rules/usirians-reaper",
  "solar radiance": "special-rules/solar-radiance",
  "thunderous charge": "special-rules/thunderous-charge",
  "zzzzap!": "special-rules/zzzzap",
  "gaze of the gods": "special-rules/gaze-of-the-gods",
  "counter charge": "special-rules/counter-charge",
  "accursed reliquary": "special-rules/accursed-reliquary",
  "woodland ambush": "special-rules/woodland-ambush",
  "arrows of isha": "special-rules/arrows-of-isha",
  "steam power": "special-rules/steam-power",
  "blasphemous tome": "special-rules/blasphemous-tome",
  "blessings of asuryan": "special-rules/blessings-of-asuryan",
  "foe render": "special-rules/foe-render",
  cumbersome: "special-rules/cumbersome",
  "herald of despair": "special-rules/herald-of-despair",
  "unbound spirits": "special-rules/unbound-spirits",
  "beam of chotec": "special-rules/beam-of-chotec",
  "the questing vow": "special-rules/the-questing-vow",
  "daemon of khorne": "special-rules/daemon-of-khorne",
  "fear of elves": "special-rules/fear-of-elves",
  "runes of protection": "special-rules/runes-of-protection",
  "marks of chaos": "special-rules/marks-of-chaos",
  "blazing body": "special-rules/blazing-body",
  "abominable attacks": "special-rules/abominable-attacks",
  temperamental: "special-rules/temperamental",
  "primeval roar": "special-rules/primeval-roar",
  "vortex of souls": "special-rules/vortex-of-souls",
  "ignore goblin panic": "special-rules/ignore-goblin-panic",
  "runes of warding": "special-rules/runes-of-warding",
  feed: "special-rules/feed",
  hellbound: "special-rules/hellbound",
  "primal fury": "special-rules/primal-fury",
  "settra's champion": "special-rules/settras-champion",
  "the grail vow": "special-rules/the-grail-vow",
  detachment: "special-rules/detachment",
  "balefire brazier": "special-rules/balefire-brazier",
  "dragon armour": "special-rules/dragon-armour",
  "mark of chaos undivided": "special-rules/mark-of-chaos-undivided",
  "daemon of nurgle": "special-rules/daemon-of-nurgle",
  "immortal overseer": "special-rules/immortal-overseer",
  "avalanche of flesh": "special-rules/avalanche-of-flesh",
  '"fight me!"': "special-rules/fight-me",
  stampede: "special-rules/stampede",
  "warped tintinnabulation": "special-rules/warped-tintinnabulation",
  "mark of khorne": "special-rules/mark-of-khorne",
  "ignore panic": "special-rules/ignore-panic",
  "two heads": "special-rules/two-heads",
  "forming the lance": "special-rules/forming-the-lance",
  "dragged along": "special-rules/dragged-along",
  "arcane vassal": "special-rules/arcane-vassal",
  "daemon of slaanesh": "special-rules/daemon-of-slaanesh",
  "razor tusks": "special-rules/razor-tusks",
  "arrows of asaph": "special-rules/arrows-of-asaph",
  "stone shaper": "special-rules/stone-shaper",
  "spectral coach": "special-rules/spectral-coach",
  "cleaving blow": "special-rules/cleaving-blow",
  "too horrible to die": "special-rules/too-horrible-to-die",
  aquatic: "special-rules/aquatic",
  "daemon of tzeentch": "special-rules/daemon-of-tzeentch",
  "mark of nurgle": "special-rules/mark-of-nurgle",
  "ithilmar armour": "special-rules/ithilmar-armour-ithilmar-barding",
  "ithilmar barding": "special-rules/ithilmar-armour-ithilmar-barding",
  "manoeuvring a lance": "special-rules/manoeuvring-a-lance",
  helblaster: "special-rules/helblaster",
  "the quickening storm": "special-rules/the-quickening-storm",
  slayer: "special-rules/slayer",
  "quell impetuosity": "special-rules/quell-impetuosity",
  drilled: "special-rules/drilled",
  ethereal: "special-rules/ethereal",
  "ithilmar weapons": "special-rules/ithilmar-weapons",
  "lightning strike": "special-rules/lightning-strike",
  "dive bomb": "special-rules/dive-bomb",
  "the lance in combat": "special-rules/the-lance-in-combat",
  "curse of the necropolis": "special-rules/curse-of-the-necropolis",
  helstorm: "special-rules/helstorm",
  "beast handlers": "special-rules/beast-handlers",
  "tusker charge": "special-rules/tusker-charge",
  "mark of slaanesh": "special-rules/mark-of-slaanesh",
  "carrion feeders": "special-rules/carrion-feeders",
  "poisoned wind": "special-rules/poisoned-wind",
  infested: "special-rules/infested",
  "waaagh!": "special-rules/waaagh",
  "blunting the lance": "special-rules/blunting-the-lance",
  "bombing run": "special-rules/bombing-run",
  "lileath's blessing": "special-rules/lileaths-blessing",
  "dry as dust": "special-rules/dry-as-dust",
  evasive: "special-rules/evasive",
  "mark of tzeentch": "special-rules/mark-of-tzeentch",
  "cold blooded": "special-rules/cold-blooded",
  warpaint: "special-rules/warpaint",
  "bestial fury": "special-rules/bestial-fury",
  "extra attacks": "special-rules/extra-attacks",
  "casualty removal": "special-rules/casualty-removal",
  deathblow: "special-rules/deathblow",
  indomitable: "special-rules/indomitable",
  "scurry away": "special-rules/scurry-away",
  "lion cloak": "special-rules/lion-cloak",
  "drop rocks": "special-rules/drop-rocks",
  "fast cavalry": "special-rules/fast-cavalry",
  "dwarf crafted": "special-rules/dwarf-crafted",
  "lance formations & skirmishers":
    "special-rules/lance-formations-and-skirmishers",
  "valour of ages": "special-rules/valour-of-ages",
  "obsidian blades": "special-rules/obsidian-blades",
  "scurrying masses": "special-rules/scurrying-masses",
  "dark vitality": "special-rules/dark-vitality",
  khopesh: "special-rules/khopesh",
  "characters joining a lance": "special-rules/characters-joining-a-lance",
  "necromantic undead": "special-rules/necromantic-undead",
  "verminous valour": "special-rules/verminous-valour",
  fear: "special-rules/fear",
  "gromril armour": "special-rules/gromril-armour",
  "nehekharan phalanx": "special-rules/nehekharan-phalanx",
  "feigned flight": "special-rules/feigned-flight",
  "warpstone weapons": "special-rules/warpstone-weapons",
  "nehekharan undead": "special-rules/nehekharan-undead",
  "the newly dead": "special-rules/the-newly-dead",
  "gromril weapons": "special-rules/gromril-weapons",
  "fight in extra rank": "special-rules/fight-in-extra-rank",
  "wailing dirge": "special-rules/wailing-dirge",
  resolute: "special-rules/resolute",
  "resurrecting the fallen": "special-rules/resurrecting-the-fallen",
  "rune lore": "special-rules/rune-lore",
  "fire & flee": "special-rules/fire-and-flee",
  "first charge": "special-rules/first-charge",
  "flaming attacks": "special-rules/flaming-attacks",
  flammable: "special-rules/flammable",
  fly: "special-rules/fly",
  frenzy: "special-rules/frenzy",
  "furious charge": "special-rules/furious-charge",
  hatred: "special-rules/hatred",
  horde: "special-rules/horde",
  howdah: "special-rules/howdah",
  "ignores cover": "special-rules/ignores-cover",
  "immune to psychology": "special-rules/immune-to-psychology",
  "impact hits": "special-rules/impact-hits",
  impetuous: "special-rules/impetuous",
  "killing blow": "special-rules/killing-blow",
  "large target": "special-rules/large-target",
  levies: "special-rules/levies",
  loner: "special-rules/loner",
  "magical attacks": "special-rules/magical-attacks",
  "magic resistance": "special-rules/magic-resistance",
  mercenaries: "special-rules/mercenaries",
  "monster handlers": "special-rules/monster-handlers",
  "monster slayer": "special-rules/monster-slayer",
  "motley crew": "special-rules/motley-crew",
  "move & shoot": "special-rules/move-and-shoot",
  "move or shoot": "special-rules/move-or-shoot",
  "move through cover": "special-rules/move-through-cover",
  "multiple shots": "special-rules/multiple-shots",
  "multiple wounds": "special-rules/multiple-wounds",
  "open order": "special-rules/open-order",
  "poisoned attacks": "special-rules/poisoned-attacks",
  ponderous: "special-rules/ponderous",
  "quick shot": "special-rules/quick-shot",
  "rallying cry": "special-rules/rallying-cry",
  "random attacks": "special-rules/random-attacks",
  "random movement": "special-rules/random-movement",
  regeneration: "special-rules/regeneration",
  "regimental unit": "special-rules/regimental-unit",
  "requires two hands": "special-rules/requires-two-hands",
  "reserve move": "special-rules/reserve-move",
  scouts: "special-rules/scouts",
  shieldwall: "special-rules/shieldwall",
  skirmishers: "special-rules/skirmishers",
  "stomp attacks": "special-rules/stomp-attacks",
  "strike first": "special-rules/strike-first",
  "strike last": "special-rules/strike-last",
  stubborn: "special-rules/stubborn",
  stupidity: "special-rules/stupidity",
  swiftstride: "special-rules/swiftstride",
  terror: "special-rules/terror",
  "timmm-berrr!": "special-rules/timmm-berrr",
  unbreakable: "special-rules/unbreakable",
  unstable: "special-rules/unstable",
  vanguard: "special-rules/vanguard",
  veteran: "special-rules/veteran",
  "volley fire": "special-rules/volley-fire",
  warband: "special-rules/warband",
  "warp-spawned": "special-rules/warp-spawned",
  "great throwing spears": "weapons-of-war/great-throwing-spears",
  "dragon fire": "weapons-of-war/dragon-fire",
  "steam cannonade": "weapons-of-war/steam-cannonade",
  "spear of loec": "weapons-of-war/spear-of-loec",
  braystaff: "weapons-of-war/braystaff",
  blunderbuss: "weapons-of-war/blunderbuss",
  "blessed triptych": "weapons-of-war/blessed-triptych",
  "ritual blade": "weapons-of-war/ritual-blade",
  "swarming mass": "weapons-of-war/swarming-mass",
  "fanatic ball & chain": "weapons-of-war/fanatic-ball-and-chain",
  "great hammer": "weapons-of-war/great-hammer",
  "steam cannon": "weapons-of-war/steam-cannon",
  "dread halberd": "weapons-of-war/dread-halberd",
  blowpipe: "weapons-of-war/blowpipe",
  bloodflail: "weapons-of-war/bloodflail",
  "warplock musket": "weapons-of-war/warplock-musket",
  "dark fire of chaos": "weapons-of-war/dark-fire-of-chaos",
  "spectral scythe": "weapons-of-war/spectral-scythe-black-coach",
  "flaming breath ogre kingdoms": "weapons-of-war/flaming-breath-ogre-kingdoms",
  "huge gob": "weapons-of-war/huge-gob",
  "filth-encrusted claws": "weapons-of-war/filth-encrusted-claws",
  "brace of drakefire pistols": "weapons-of-war/brace-of-drakefire-pistols",
  polearm: "weapons-of-war/polearm",
  "warplock pistol": "weapons-of-war/warplock-pistol",
  "steam gun empire": "weapons-of-war/steam-gun-empire",
  "slythey tongue": "weapons-of-war/slythey-tongue",
  "trickster's blades": "weapons-of-war/tricksters-blades",
  bombard: "weapons-of-war/bombard",
  greatbow: "weapons-of-war/greatbow",
  "handmaiden's spear": "weapons-of-war/handmaidens-spear",
  "great axe": "weapons-of-war/great-axe",
  "trampling hooves": "weapons-of-war/trampling-hooves",
  "fumes of contagion": "weapons-of-war/fumes-of-contagion",
  "fiery breath lizardmen": "weapons-of-war/fiery-breath-lizardmen",
  "har ganeth greatsword": "weapons-of-war/har-ganeth-greatsword",
  "horns of stone": "weapons-of-war/horns-of-stone",
  "eagle-eye bolt thrower": "weapons-of-war/eagle-eye-bolt-thrower",
  "burning braziers": "weapons-of-war/burning-braziers",
  "troll vomit": "weapons-of-war/troll-vomit",
  drakegun: "weapons-of-war/drakegun",
  "goring horns": "weapons-of-war/goring-horns",
  "flaming breath warriors of chaos":
    "weapons-of-war/flaming-breath-warriors-of-chaos",
  "lash of khorne": "weapons-of-war/lash-of-khorne",
  "petrifying gaze": "weapons-of-war/petrifying-gaze",
  "razor barbs": "weapons-of-war/razor-barbs",
  "serrated maw": "weapons-of-war/serrated-maw",
  "writhing tail": "weapons-of-war/writhing-tail",
  "lash & buckler": "weapons-of-war/lash-and-buckler",
  "plague censer": "weapons-of-war/plague-censer",
  "oaken fists": "weapons-of-war/oaken-fists",
  strangleroots: "weapons-of-war/strangleroots",
  "ravager harpoon": "weapons-of-war/ravager-harpoon",
  "doom-flayer": "weapons-of-war/doom-flayer",
  "fiend tail": "weapons-of-war/fiend-tail",
  "hand weapon": "weapons-of-war/hand-weapon",
  "great tusks": "weapons-of-war/great-tusks",
  "bow of avelorn": "weapons-of-war/bow-of-avelorn",
  "pestilential breath": "weapons-of-war/pestilential-breath",
  "brass bound hooves": "weapons-of-war/brass-bound-hooves",
  "breath of desiccation": "weapons-of-war/breath-of-desiccation",
  "helblaster volley gun": "weapons-of-war/helblaster-volley-gun",
  "acidic vomit": "weapons-of-war/acidic-vomit",
  "fireleech bolas": "weapons-of-war/fireleech-bolas",
  "mace tail": "weapons-of-war/mace-tail",
  "defensive stakes": "weapons-of-war/defensive-stakes",
  "cinderblast bombs": "weapons-of-war/cinderblast-bombs",
  "wicked claws": "weapons-of-war/wicked-claws",
  "ceremonial halberd": "weapons-of-war/ceremonial-halberd",
  "envenomed sting": "weapons-of-war/envenomed-sting",
  "filth-encrusted talons": "weapons-of-war/filth-encrusted-talons",
  "two hand weapons": "weapons-of-war/two-hand-weapons-additional-hand-weapon",
  "additional hand weapon":
    "weapons-of-war/two-hand-weapons-additional-hand-weapon",
  "poisoned wind mortar": "weapons-of-war/poisoned-wind-mortar",
  "chill breath": "weapons-of-war/chill-breath",
  "slashing talons": "weapons-of-war/slashing-talons",
  "noxious breath": "weapons-of-war/noxious-breath",
  "venomous tail": "weapons-of-war/venomous-tail",
  doomfire: "weapons-of-war/doomfire",
  "cannon of khorne": "weapons-of-war/cannon-of-khorne",
  "sorcerous exhalation": "weapons-of-war/sorcerous-exhalation",
  "hurl attack": "weapons-of-war/hurl-attack",
  "mighty antlers": "weapons-of-war/mighty-antlers",
  "field trebuchet": "weapons-of-war/field-trebuchet",
  "helstorm rocket battery": "weapons-of-war/helstorm-rocket-battery",
  "trollhammer torpedo": "weapons-of-war/trollhammer-torpedo",
  "blasting charges": "weapons-of-war/blasting-charges",
  "venom surge": "weapons-of-war/venom-surge",
  "chracian great blade": "weapons-of-war/chracian-great-blade",
  "great horns": "weapons-of-war/great-horns",
  bilesword: "weapons-of-war/bilesword",
  flail: "weapons-of-war/flail",
  "fiery roar": "weapons-of-war/fiery-roar",
  "serrated maws": "weapons-of-war/serrated-maws",
  "demolition rockets": "weapons-of-war/demolition-rockets",
  "asrai spear": "weapons-of-war/asrai-spear",
  "cleaver-limbs": "weapons-of-war/cleaver-limbs",
  "rancid maw": "weapons-of-war/rancid-maw",
  "ratling gun": "weapons-of-war/ratling-gun",
  "leadbelcher gun": "weapons-of-war/leadbelcher-gun",
  "grenade launching blunderbuss":
    "weapons-of-war/grenade-launching-blunderbuss",
  "great weapon": "weapons-of-war/great-weapon",
  "grimfrost weapon": "weapons-of-war/grimfrost-weapon",
  "ranger's glaive": "weapons-of-war/rangers-glaive",
  plagueflail: "weapons-of-war/plagueflail",
  "fiery breath dark elves": "weapons-of-war/fiery-breath-dark-elves",
  "spidersilk lobber": "weapons-of-war/spidersilk-lobber",
  "giant bow": "weapons-of-war/giant-bow",
  "steam drill": "weapons-of-war/steam-drill",
  "poisonous tail": "weapons-of-war/poisonous-tail",
  "hochland long rifle": "weapons-of-war/hochland-long-rifle",
  "infernal incendiaries": "weapons-of-war/infernal-incendiaries",
  "warpfire thrower": "weapons-of-war/warpfire-thrower",
  "decapitating claws": "weapons-of-war/decapitating-claws",
  "sword of hoeth": "weapons-of-war/sword-of-hoeth",
  "colossal fang-filled gob": "weapons-of-war/colossal-fang-filled-gob",
  "writhing tentacles daemons of chaos":
    "weapons-of-war/writhing-tentacles-daemons-of-chaos",
  "cavernous maw": "weapons-of-war/cavernous-maw",
  "giant blowpipes": "weapons-of-war/giant-blowpipes",
  "dreadquake mortar": "weapons-of-war/dreadquake-mortar",
  halberd: "weapons-of-war/halberd",
  "monstrous tusks": "weapons-of-war/monstrous-tusks",
  "warp grinder": "weapons-of-war/warp-grinder",
  "blackbriar javelin": "weapons-of-war/blackbriar-javelin",
  "pigeon bombs": "weapons-of-war/pigeon-bombs",
  "steam gun dwarfs": "weapons-of-war/steam-gun-dwarfs",
  "paired great khopeshes": "weapons-of-war/paired-great-khopeshes",
  "giant's club": "weapons-of-war/giants-club",
  "doom diver": "weapons-of-war/doom-diver",
  "morning star": "weapons-of-war/morning-star",
  "cannon of the sky-titans": "weapons-of-war/cannon-of-the-sky-titans",
  "warplock jezzail": "weapons-of-war/warplock-jezzail",
  "hunting spear": "weapons-of-war/hunting-spear",
  "cleaing blades": "weapons-of-war/cleaing-blades",
  "blood of hashut": "weapons-of-war/blood-of-hashut",
  "plague proboscis": "weapons-of-war/plague-proboscis",
  "writhing tentacles dark elves":
    "weapons-of-war/writhing-tentacles-dark-elves",
  "brimstone gun": "weapons-of-war/brimstone-gun",
  "thunderous bludgeon": "weapons-of-war/thunderous-bludgeon",
  "darkforged weapon": "weapons-of-war/darkforged-weapon",
  clattergun: "weapons-of-war/clattergun",
  "venom sting": "weapons-of-war/venom-sting",
  "venomous talons": "weapons-of-war/venomous-talons",
  "poisoned wind globes": "weapons-of-war/poisoned-wind-globes",
  whip: "weapons-of-war/whip",
  "scraplauncher catapult": "weapons-of-war/scraplauncher-catapult",
  "decapitating strike": "weapons-of-war/decapitating-strike",
  "soporific breath": "weapons-of-war/soporific-breath",
  chaintrap: "weapons-of-war/chaintrap",
  "asrai longbow": "weapons-of-war/asrai-longbow",
  fireglaive: "weapons-of-war/fireglaive",
  "impaling claws": "weapons-of-war/impaling-claws",
  "things-catcher": "weapons-of-war/things-catcher",
  "screaming skull catapult": "weapons-of-war/screaming-skull-catapult",
  "venom spray": "weapons-of-war/venom-spray",
  "tzeentchian wand": "weapons-of-war/tzeentchian-wand",
  "blood vulture": "weapons-of-war/blood-vulture",
  "hailshot blunderbuss": "weapons-of-war/hailshot-blunderbuss",
  lance: "weapons-of-war/lance",
  "enchanted arrows": "weapons-of-war/enchanted-arrows",
  "billowing death": "weapons-of-war/billowing-death",
  "cavalry spear": "weapons-of-war/cavalry-spear",
  "warpstone claws": "weapons-of-war/warpstone-claws",
  "distensible jaw": "weapons-of-war/distensible-jaw",
  warpflame: "weapons-of-war/warpflame",
  "naptha bombs": "weapons-of-war/naptha-bombs",
  "arcane bodkins": "weapons-of-war/arcane-bodkins",
  "hagbane tips": "weapons-of-war/hagbane-tips",
  "warp lightning cannon": "weapons-of-war/warp-lightning-cannon",
  "ensorcelled weapon": "weapons-of-war/ensorcelled-weapon",
  "harpoon launcher": "weapons-of-war/harpoon-launcher",
  "throwing spear": "weapons-of-war/throwing-spear",
  "moonfire shot": "weapons-of-war/moonfire-shot",
  ironfist: "weapons-of-war/ironfist",
  "plagueclaw catapult": "weapons-of-war/plagueclaw-catapult",
  "thrusting spear": "weapons-of-war/thrusting-spear",
  "daemonic talons": "weapons-of-war/daemonic-talons",
  "iron claw": "weapons-of-war/iron-claw",
  "ogre pistol": "weapons-of-war/ogre-pistol",
  "swiftshiver shards": "weapons-of-war/swiftshiver-shards",
  "brace of ogre pistols": "weapons-of-war/brace-of-ogre-pistols",
  "harvester cannon": "weapons-of-war/harvester-cannon",
  "trueflight arrows": "weapons-of-war/trueflight-arrows",
  "baleful torrent": "weapons-of-war/baleful-torrent",
  longbow: "weapons-of-war/longbow",
  "warp gaze": "weapons-of-war/warp-gaze",
  hellblade: "weapons-of-war/hellblade",
  shortbow: "weapons-of-war/shortbow",
  warbow: "weapons-of-war/warbow",
  plaguesword: "weapons-of-war/plaguesword",
  "death's heads": "weapons-of-war/deaths-heads",
  handgun: "weapons-of-war/handgun",
  "piercing claws": "weapons-of-war/piercing-claws",
  "flames of tzeentch": "weapons-of-war/flames-of-tzeentch",
  pistol: "weapons-of-war/pistol",
  "brace of pistols": "weapons-of-war/brace-of-pistols",
  "lamprey's bite": "weapons-of-war/lampreys-bite",
  "repeater handgun": "weapons-of-war/repeater-handgun",
  "repeater pistol": "weapons-of-war/repeater-pistol",
  crossbow: "weapons-of-war/crossbow",
  "repeater crossbow": "weapons-of-war/repeater-crossbow",
  "repeater handbow": "weapons-of-war/repeater-handbow",
  "brace of repeater handbows": "weapons-of-war/brace-of-repeater-handbows",
  "throwing weapons": "weapons-of-war/throwing-weapons",
  javelin: "weapons-of-war/javelin",
  sling: "weapons-of-war/sling",
  "throwing axe": "weapons-of-war/throwing-axe",
  "light armour": "weapons-of-war/light-armour",
  "heavy armour": "weapons-of-war/heavy-armour",
  "full plate armour": "weapons-of-war/full-plate-armour",
  shield: "weapons-of-war/shield",
  barding: "weapons-of-war/barding",
  "lore of undeath": "the-lores-of-magic/lore-of-undeath",
  "lore of the horned rat": "the-lores-of-magic/lore-of-the-horned-rat",
  "lore of the great maw": "the-lores-of-magic/lore-of-the-great-maw",
  "lore of lustria": "the-lores-of-magic/lore-of-lustria",
  "lore of naggaroth": "the-lores-of-magic/lore-of-naggaroth",
  "lore of daemons": "the-lores-of-magic/lore-of-daemons",
  "lore of hashut": "the-lores-of-magic/lore-of-hashut",
  "lore of saphery": "the-lores-of-magic/lore-of-saphery",
  "lore of athel loren": "the-lores-of-magic/lore-of-athel-loren",
  "lore of the lady": "the-lores-of-magic/lore-of-the-lady",
  "lore of nehekhara": "the-lores-of-magic/lore-of-nehekhara",
  "lore of chaos": "the-lores-of-magic/lore-of-chaos",
  "lore of gork": "the-lores-of-magic/lore-of-gork",
  "lore of beasts": "the-lores-of-magic/lore-of-beasts",
  "lore of mork": "the-lores-of-magic/lore-of-mork",
  "battle magic": "the-lores-of-magic/battle-magic",
  daemonology: "the-lores-of-magic/daemonology",
  "dark magic": "the-lores-of-magic/dark-magic",
  elementalism: "the-lores-of-magic/elementalism",
  "high magic": "the-lores-of-magic/high-magic",
  illusion: "the-lores-of-magic/illusion",
  necromancy: "the-lores-of-magic/necromancy",
  "waaagh! magic": "the-lores-of-magic/waaagh-magic",
  "'eadbuttin' 'at": "magic-item/eadbuttin-at",
  "a befuddlement of mischiefs": "magic-item/a-befuddlement-of-mischiefs",
  "a blight of terrors": "magic-item/a-blight-of-terrors",
  "a lamentation of despairs": "magic-item/a-lamentation-of-despairs",
  "a murder of spites": "magic-item/a-murder-of-spites",
  "a muster of malevolents": "magic-item/a-muster-of-malevolents",
  "a resplendence of luminescents": "magic-item/a-resplendence-of-luminescents",
  "acid ichor": "magic-item/acid-ichor",
  "æther blade": "magic-item/aether-blade",
  "allure of slaanesh": "magic-item/allure-of-slaanesh",
  "amulet of the serpent": "magic-item/amulet-of-the-serpent",
  "an annoyance of netlings": "magic-item/an-annoyance-of-netlings",
  "annulian crystal": "magic-item/annulian-crystal",
  "anointed armour": "magic-item/anointed-armour",
  "anointed of asuryan": "magic-item/anointed-of-asuryan",
  "antlers of the great hunt": "magic-item/antlers-of-the-great-hunt",
  "arcane familiar": "magic-item/arcane-familiar",
  "armour of bazherak the cruel": "magic-item/armour-of-bazherak-the-cruel",
  "armour of caledor": "magic-item/armour-of-caledor",
  "armour of destiny": "magic-item/armour-of-destiny",
  "armour of fortune": "magic-item/armour-of-fortune",
  "armour of khorne": "magic-item/armour-of-khorne",
  "armour of meteoric iron": "magic-item/armour-of-meteoric-iron",
  "armour of mork": "magic-item/armour-of-mork",
  "armour of silvered steel": "magic-item/armour-of-silvered-steel",
  "armour of tarnus": "magic-item/armour-of-tarnus",
  "armour of the ages": "magic-item/armour-of-the-ages",
  "armour of the damned": "magic-item/armour-of-the-damned",
  "ashen banner": "magic-item/ashen-banner",
  "asyendi's bane": "magic-item/asyendis-bane",
  "aura of pain": "magic-item/aura-of-pain",
  "aura of quetzl": "magic-item/aura-of-quetzl",
  "axe of khorne": "magic-item/axe-of-khorne",
  "axe of men": "magic-item/axe-of-men",
  "banner of acquiescence": "magic-item/banner-of-acquiescence",
  "banner of arcane protection": "magic-item/banner-of-arcane-protection",
  "banner of châlons": "magic-item/banner-of-chalons",
  "banner of change": "magic-item/banner-of-change",
  "banner of discord": "magic-item/banner-of-discord",
  "banner of duty": "magic-item/banner-of-duty",
  "banner of ellyrion": "magic-item/banner-of-ellyrion",
  "banner of har ganeth": "magic-item/banner-of-har-ganeth",
  "banner of honourable warfare": "magic-item/banner-of-honourable-warfare",
  "banner of iron resolve": "magic-item/banner-of-iron-resolve",
  "banner of midsummer's eve": "magic-item/banner-of-midsummers-eve",
  "banner of nagarythe": "magic-item/banner-of-nagarythe",
  "banner of outrage": "magic-item/banner-of-outrage",
  "banner of rage": "magic-item/banner-of-rage",
  "banner of the barrows": "magic-item/banner-of-the-barrows",
  "banner of the desert winds": "magic-item/banner-of-the-desert-winds",
  "banner of the eternal queen": "magic-item/banner-of-the-eternal-queen",
  "banner of the gods": "magic-item/banner-of-the-gods",
  "banner of the hunter king": "magic-item/banner-of-the-hunter-king",
  "banner of the lady's grace": "magic-item/banner-of-the-ladys-grace",
  "banner of the wildwood": "magic-item/banner-of-the-wildwood",
  "banner of the zealous knight": "magic-item/banner-of-the-zealous-knight",
  "banner of unholy victory": "magic-item/banner-of-unholy-victory",
  "banner of verminous scurrying": "magic-item/banner-of-verminous-scurrying",
  "battle banner": "magic-item/battle-banner",
  "battleaxe of the last big waaagh!":
    "magic-item/battleaxe-of-the-last-big-waaagh",
  beastkiller: "magic-item/beastkiller",
  "becalming cogitation": "magic-item/becalming-cogitation",
  "bedazzling helm": "magic-item/bedazzling-helm",
  beguile: "magic-item/beguile",
  "berserker blade": "magic-item/berserker-blade",
  "big boss 'at": "magic-item/big-boss-at",
  "biting blade": "magic-item/biting-blade",
  "black dragon egg": "magic-item/black-dragon-egg",
  "black hammer of hashut": "magic-item/black-hammer-of-hashut",
  "black staff": "magic-item/black-staff",
  "blade of antarhak": "magic-item/blade-of-antarhak",
  "blade of nurglitch": "magic-item/blade-of-nurglitch",
  "blade of revered tzunki": "magic-item/blade-of-revered-tzunki",
  "blades of loec": "magic-item/blades-of-loec",
  "blasted standard": "magic-item/blasted-standard",
  "blood armour": "magic-item/blood-armour",
  "blood drinker": "magic-item/blood-drinker",
  "blood of caledor": "magic-item/blood-of-caledor",
  bloodcleaver: "magic-item/bloodcleaver",
  "book of ashur": "magic-item/book-of-ashur",
  "bow of loren": "magic-item/bow-of-loren",
  "brass orb": "magic-item/brass-orb",
  "brazen collar": "magic-item/brazen-collar",
  "breath of hashut": "magic-item/breath-of-hashut",
  "bull standard": "magic-item/bull-standard",
  "burning blade": "magic-item/burning-blade",
  "buzgob's knobbly staff": "magic-item/buzgobs-knobbly-staff",
  "cannibal totem": "magic-item/cannibal-totem",
  "cathayan jet pendant": "magic-item/cathayan-jet-pendant",
  "cautious shield": "magic-item/cautious-shield",
  "chalice of brionne": "magic-item/chalice-of-brionne",
  "chaos runesword": "magic-item/chaos-runesword",
  "charmed shield": "magic-item/charmed-shield",
  "chracian hunter": "magic-item/chracian-hunter",
  "cloak of feathers": "magic-item/cloak-of-feathers",
  "cloak of mist & shadows": "magic-item/cloak-of-mist-and-shadows",
  "cloak of the dunes": "magic-item/cloak-of-the-dunes",
  "cold-blooded banner": "magic-item/cold-blooded-banner",
  "collar of khorne": "magic-item/collar-of-khorne",
  "collar of shapesh": "magic-item/collar-of-shapesh",
  "conqueror's tapestry": "magic-item/conquerors-tapestry",
  "crimson armour of dargan": "magic-item/crimson-armour-of-dargan",
  "crook & flail of radiance": "magic-item/crook-and-flail-of-radiance",
  "crown of everlasting conquest": "magic-item/crown-of-everlasting-conquest",
  "crown of horns": "magic-item/crown-of-horns",
  "crown of kings": "magic-item/crown-of-kings",
  "crown of the damned": "magic-item/crown-of-the-damned",
  "crusader's clarion": "magic-item/crusaders-clarion",
  "crusader's lance": "magic-item/crusaders-lance",
  "crusader's tapestry": "magic-item/crusaders-tapestry",
  "cube of darkness": "magic-item/cube-of-darkness",
  "cupped hands of the old ones": "magic-item/cupped-hands-of-the-old-ones",
  "curse of the revenant": "magic-item/curse-of-the-revenant",
  "curse-weaver wand": "magic-item/curse-weaver-wand",
  "da banner of butchery": "magic-item/da-banner-of-butchery",
  "da choppiest choppa": "magic-item/da-choppiest-choppa",
  "daemon flask": "magic-item/daemon-flask",
  "daemon-flesh": "magic-item/daemon-flesh",
  "daemon-slayer scars": "magic-item/daemon-slayer-scars",
  "daemonic familiar": "magic-item/daemonic-familiar",
  "daemonic robes": "magic-item/daemonic-robes",
  daemonsword: "magic-item/daemonsword",
  "dagger of malice": "magic-item/dagger-of-malice",
  "dark acolyte": "magic-item/dark-acolyte",
  "dark heart": "magic-item/dark-heart",
  "dark majesty": "magic-item/dark-majesty",
  "dark maul": "magic-item/dark-maul",
  dawnstone: "magic-item/dawnstone",
  "death globe": "magic-item/death-globe",
  "death mask of kharnutt": "magic-item/death-mask-of-kharnutt",
  deathcheater: "magic-item/deathcheater",
  "deepwood sphere": "magic-item/deepwood-sphere",
  "destroyer of eternities": "magic-item/destroyer-of-eternities",
  "diabolic splendour": "magic-item/diabolic-splendour",
  "diadem of power": "magic-item/diadem-of-power",
  "dispel scroll": "magic-item/dispel-scroll",
  "doom totem": "magic-item/doom-totem",
  "dragon bow": "magic-item/dragon-bow",
  "dragon helm": "magic-item/dragon-helm",
  "dragon slaying sword": "magic-item/dragon-slaying-sword",
  "dragonhide banner": "magic-item/dragonhide-banner",
  "dragonhide cloak": "magic-item/dragonhide-cloak",
  "drakenhof banner": "magic-item/drakenhof-banner",
  dreadlance: "magic-item/dreadlance",
  "duellist's blades": "magic-item/duellists-blades",
  "dwarf hide banner": "magic-item/dwarf-hide-banner",
  "earthing rod": "magic-item/earthing-rod",
  "enchanted shield": "magic-item/enchanted-shield",
  "enchanting aura": "magic-item/enchanting-aura",
  "enkhil's kanopi": "magic-item/enkhils-kanopi",
  "enrapturing gaze": "magic-item/enrapturing-gaze",
  "errantry banner": "magic-item/errantry-banner",
  "executioner's axe": "magic-item/executioners-axe",
  "extra arm": "magic-item/extra-arm",
  "falcon-horn of fredemund": "magic-item/falcon-horn-of-fredemund",
  "favour of the gods": "magic-item/favour-of-the-gods",
  "feedback scroll": "magic-item/feedback-scroll",
  "filth mace": "magic-item/filth-mace",
  "fistful of laurels": "magic-item/fistful-of-laurels",
  "flail of skulls": "magic-item/flail-of-skulls",
  "flamestrike wand": "magic-item/flamestrike-wand",
  "flying carpet": "magic-item/flying-carpet",
  "flying horror": "magic-item/flying-horror",
  "focus familiar": "magic-item/focus-familiar",
  "foe bane": "magic-item/foe-bane",
  foebreaker: "magic-item/foebreaker",
  "frontier axe": "magic-item/frontier-axe",
  frostblade: "magic-item/frostblade",
  "fungus wine": "magic-item/fungus-wine",
  "gauntlet of the duel": "magic-item/gauntlet-of-the-duel",
  "giant blade": "magic-item/giant-blade",
  giantbreaker: "magic-item/giantbreaker",
  "gilded cuirass": "magic-item/gilded-cuirass",
  glamourweave: "magic-item/glamourweave",
  "glittering scales": "magic-item/glittering-scales",
  "glittering wotnots": "magic-item/glittering-wotnots",
  "glowy green amulet": "magic-item/glowy-green-amulet",
  "glyph necklace": "magic-item/glyph-necklace",
  "gnarled hide": "magic-item/gnarled-hide",
  "gouge-tusks": "magic-item/gouge-tusks",
  "grail pendant": "magic-item/grail-pendant",
  "grand banner of superiority": "magic-item/grand-banner-of-superiority",
  "great standard of sundering": "magic-item/great-standard-of-sundering",
  "griffon standard": "magic-item/griffon-standard",
  "gromril great helm": "magic-item/gromril-great-helm",
  "grudge rune": "magic-item/grudge-rune",
  "grut's sickle": "magic-item/gruts-sickle",
  "guff's windy banner": "magic-item/guffs-windy-banner",
  "gut maw": "magic-item/gut-maw",
  "hagtree fetish": "magic-item/hagtree-fetish",
  "hail of doom arrow": "magic-item/hail-of-doom-arrow",
  "halfling cookbook": "magic-item/halfling-cookbook",
  "hand of dust": "magic-item/hand-of-dust",
  "harrowing scrutiny": "magic-item/harrowing-scrutiny",
  "headsman's axe": "magic-item/headsmans-axe",
  "healing potion": "magic-item/healing-potion",
  "heart of the wilds": "magic-item/heart-of-the-wilds",
  "heartwood lance": "magic-item/heartwood-lance",
  hellheart: "magic-item/hellheart",
  hellshard: "magic-item/hellshard",
  "helm of commandment": "magic-item/helm-of-commandment",
  "helm of many eyes": "magic-item/helm-of-many-eyes",
  "helm of the hunt": "magic-item/helm-of-the-hunt",
  "hide of the cold ones": "magic-item/hide-of-the-cold-ones",
  "hieratic jar": "magic-item/hieratic-jar",
  "higher state of mind": "magic-item/higher-state-of-mind",
  "horn of the first beast": "magic-item/horn-of-the-first-beast",
  "horned one": "magic-item/horned-one",
  "hunter's spear": "magic-item/hunters-spear",
  "hydra's tooth": "magic-item/hydras-tooth",
  "icon of endless war": "magic-item/icon-of-endless-war",
  "icon of eternal virulence": "magic-item/icon-of-eternal-virulence",
  "icon of rakaph": "magic-item/icon-of-rakaph",
  "icon of rulership": "magic-item/icon-of-rulership",
  "icon of sorcery": "magic-item/icon-of-sorcery",
  "icon of the sacred eye": "magic-item/icon-of-the-sacred-eye",
  "idol of mork": "magic-item/idol-of-mork",
  "imperial banner": "magic-item/imperial-banner",
  "infernal enrapturess": "magic-item/infernal-enrapturess",
  "infernal puppet": "magic-item/infernal-puppet",
  "iridescent corona": "magic-item/iridescent-corona",
  "ironspike shield": "magic-item/ironspike-shield",
  "itxi grub": "magic-item/itxi-grub",
  "jade amulet": "magic-item/jade-amulet",
  "jade lion": "magic-item/jade-lion",
  "jagged dagger": "magic-item/jagged-dagger",
  "jaguar standard": "magic-item/jaguar-standard",
  kineater: "magic-item/kineater",
  "laurels of victory": "magic-item/laurels-of-victory",
  lifetaker: "magic-item/lifetaker",
  "lion standard": "magic-item/lion-standard",
  longstrider: "magic-item/longstrider",
  "lord of the night": "magic-item/lord-of-the-night",
  "lore familiar": "magic-item/lore-familiar",
  loremaster: "magic-item/loremaster",
  luckstone: "magic-item/luckstone",
  "lucky heirloom": "magic-item/lucky-heirloom",
  "mace of helsturm": "magic-item/mace-of-helsturm",
  "manbane standard": "magic-item/manbane-standard",
  mangelder: "magic-item/mangelder",
  "mantle of stone": "magic-item/mantle-of-stone",
  "mantle of the damsel elena": "magic-item/mantle-of-the-damsel-elena",
  "many arms": "magic-item/many-arms",
  "many-limbed fiend": "magic-item/many-limbed-fiend",
  "master of mortals": "magic-item/master-of-mortals",
  "master of the black arts": "magic-item/master-of-the-black-arts",
  "master rune of adamant": "magic-item/master-rune-of-adamant",
  "master rune of alaric the mad": "magic-item/master-rune-of-alaric-the-mad",
  "master rune of balance": "magic-item/master-rune-of-balance",
  "master rune of breaking": "magic-item/master-rune-of-breaking",
  "master rune of calm": "magic-item/master-rune-of-calm",
  "master rune of disguise": "magic-item/master-rune-of-disguise",
  "master rune of dragon slaying": "magic-item/master-rune-of-dragon-slaying",
  "master rune of flight": "magic-item/master-rune-of-flight",
  "master rune of gromril": "magic-item/master-rune-of-gromril",
  "master rune of grungni": "magic-item/master-rune-of-grungni",
  "master rune of hesitation": "magic-item/master-rune-of-hesitation",
  "master rune of immolation": "magic-item/master-rune-of-immolation",
  "master rune of skalf blackhammer":
    "magic-item/master-rune-of-skalf-blackhammer",
  "master rune of smiting": "magic-item/master-rune-of-smiting",
  "master rune of spite": "magic-item/master-rune-of-spite",
  "master rune of stromni redbeard":
    "magic-item/master-rune-of-stromni-redbeard",
  "master rune of swiftness": "magic-item/master-rune-of-swiftness",
  "mastodon armour": "magic-item/mastodon-armour",
  mawseeker: "magic-item/mawseeker",
  "merciw's locus": "magic-item/merciws-locus",
  "might of khorne": "magic-item/might-of-khorne",
  "mirage banner": "magic-item/mirage-banner",
  "morning star of fracasse": "magic-item/morning-star-of-fracasse",
  mountaineater: "magic-item/mountaineater",
  "muscular monstrosity": "magic-item/muscular-monstrosity",
  "null stone": "magic-item/null-stone",
  "nurgling infestation": "magic-item/nurgling-infestation",
  "oaken stave": "magic-item/oaken-stave",
  "obsidian lodestone": "magic-item/obsidian-lodestone",
  "obsidian vambraces": "magic-item/obsidian-vambraces",
  "ogre blade": "magic-item/ogre-blade",
  "opal amulet": "magic-item/opal-amulet",
  "orb of ptra": "magic-item/orb-of-ptra",
  "overseer's sigil": "magic-item/overseers-sigil",
  "paymaster's coin": "magic-item/paymasters-coin",
  "pearl of infinite bleakness": "magic-item/pearl-of-infinite-bleakness",
  "pelt of midnight": "magic-item/pelt-of-midnight",
  "pelt of the dark young": "magic-item/pelt-of-the-dark-young",
  "pendant of damnation": "magic-item/pendant-of-damnation",
  "pendant of khaeleth": "magic-item/pendant-of-khaeleth",
  "phakth's blades of justice": "magic-item/phakths-blades-of-justice",
  "phâzerakt's kanopi": "magic-item/phazerakts-kanopi",
  "piranha blade": "magic-item/piranha-blade",
  "poisonous slime": "magic-item/poisonous-slime",
  "porko's pigstikka": "magic-item/porkos-pigstikka",
  "potion of foolhardiness": "magic-item/potion-of-foolhardiness",
  "potion of speed": "magic-item/potion-of-speed",
  "potion of strength": "magic-item/potion-of-strength",
  "potion of toughness": "magic-item/potion-of-toughness",
  "power scroll": "magic-item/power-scroll",
  "power vortex": "magic-item/power-vortex",
  "prayer icon of quenelles": "magic-item/prayer-icon-of-quenelles",
  "primeval club": "magic-item/primeval-club",
  "pure of heart": "magic-item/pure-of-heart",
  "railarian's mantle": "magic-item/railarians-mantle",
  "rampaging banner": "magic-item/rampaging-banner",
  "rapturous standard": "magic-item/rapturous-standard",
  "razor standard": "magic-item/razor-standard",
  "reaver bow": "magic-item/reaver-bow",
  "relic of the desert sun": "magic-item/relic-of-the-desert-sun",
  "rotten icon": "magic-item/rotten-icon",
  "royal mantle": "magic-item/royal-mantle",
  "royal standard of settra": "magic-item/royal-standard-of-settra",
  "ruby ring of ruin": "magic-item/ruby-ring-of-ruin",
  "rune maw": "magic-item/rune-maw",
  "rune of banishment": "magic-item/rune-of-banishment",
  "rune of battle": "magic-item/rune-of-battle",
  "rune of burning": "magic-item/rune-of-burning",
  "rune of cleaving": "magic-item/rune-of-cleaving",
  "rune of confusion": "magic-item/rune-of-confusion",
  "rune of courage": "magic-item/rune-of-courage",
  "rune of fear": "magic-item/rune-of-fear",
  "rune of fire": "magic-item/rune-of-fire",
  "rune of forging": "magic-item/rune-of-forging",
  "rune of fortitude": "magic-item/rune-of-fortitude",
  "rune of fury": "magic-item/rune-of-fury",
  "rune of iron": "magic-item/rune-of-iron",
  "rune of luck": "magic-item/rune-of-luck",
  "rune of might": "magic-item/rune-of-might",
  "rune of parrying": "magic-item/rune-of-parrying",
  "rune of passage": "magic-item/rune-of-passage",
  "rune of preservation": "magic-item/rune-of-preservation",
  "rune of reloading": "magic-item/rune-of-reloading",
  "rune of shielding": "magic-item/rune-of-shielding",
  "rune of skewering": "magic-item/rune-of-skewering",
  "rune of speed": "magic-item/rune-of-speed",
  "rune of spellbreaking": "magic-item/rune-of-spellbreaking",
  "rune of stone": "magic-item/rune-of-stone",
  "rune of striking": "magic-item/rune-of-striking",
  "rune of the beast ascendant": "magic-item/rune-of-the-beast-ascendant",
  "rune of the furnace": "magic-item/rune-of-the-furnace",
  "rune of the true beast": "magic-item/rune-of-the-true-beast",
  "rune of warding": "magic-item/rune-of-warding",
  runefang: "magic-item/runefang",
  "sacrament of the lady": "magic-item/sacrament-of-the-lady",
  "scarab brooch": "magic-item/scarab-brooch",
  "sceptre of de noirot": "magic-item/sceptre-of-de-noirot",
  "scimitar of the sun resplendent":
    "magic-item/scimitar-of-the-sun-resplendent",
  "scroll of binding": "magic-item/scroll-of-binding",
  "scroll of transmogrification": "magic-item/scroll-of-transmogrification",
  "sea guard": "magic-item/sea-guard",
  "seed of rebirth": "magic-item/seed-of-rebirth",
  "serpent staff": "magic-item/serpent-staff",
  "shadow magnet": "magic-item/shadow-magnet",
  "shadow stalker": "magic-item/shadow-stalker",
  "shield of ghrond": "magic-item/shield-of-ghrond",
  "shield of ptra": "magic-item/shield-of-ptra",
  "shield of the mirror pool": "magic-item/shield-of-the-mirror-pool",
  "shield of the warrior true": "magic-item/shield-of-the-warrior-true",
  "shroud of iron": "magic-item/shroud-of-iron",
  "shroud of the ancestor": "magic-item/shroud-of-the-ancestor",
  "sigil of asuryan": "magic-item/sigil-of-asuryan",
  "sigil of centuries": "magic-item/sigil-of-centuries",
  "silver mirror": "magic-item/silver-mirror",
  "silvery wand": "magic-item/silvery-wand",
  "siren song": "magic-item/siren-song",
  "siren standard": "magic-item/siren-standard",
  "sirienne's locket": "magic-item/siriennes-locket",
  skalm: "magic-item/skalm",
  skavenbrew: "magic-item/skavenbrew",
  "skavenpelt banner": "magic-item/skavenpelt-banner",
  "skin of man": "magic-item/skin-of-man",
  "skull of katam": "magic-item/skull-of-katam",
  "skull staff": "magic-item/skull-staff",
  "skull totem": "magic-item/skull-totem",
  skullplucker: "magic-item/skullplucker",
  "sloppity bilepiper": "magic-item/sloppity-bilepiper",
  "slug-skin": "magic-item/slug-skin",
  "soporific musk": "magic-item/soporific-musk",
  "sorcerous void": "magic-item/sorcerous-void",
  "sorrow's end": "magic-item/sorrows-end",
  "soul of stone": "magic-item/soul-of-stone",
  spangleshard: "magic-item/spangleshard",
  "spear of twilight": "magic-item/spear-of-twilight",
  "spell eater": "magic-item/spell-eater",
  "spell familiar": "magic-item/spell-familiar",
  "spelleater axe": "magic-item/spelleater-axe",
  spellshield: "magic-item/spellshield",
  "spellthieving sword": "magic-item/spellthieving-sword",
  "spoilpox scrivener": "magic-item/spoilpox-scrivener",
  "staff of aeons": "magic-item/staff-of-aeons",
  "staff of awakening": "magic-item/staff-of-awakening",
  "staff of change": "magic-item/staff-of-change",
  "staff of the lost sun": "magic-item/staff-of-the-lost-sun",
  "stalwart rune": "magic-item/stalwart-rune",
  "standard of chaotic glory": "magic-item/standard-of-chaotic-glory",
  "standard of hellish vigour": "magic-item/standard-of-hellish-vigour",
  "standard of seeping decay": "magic-item/standard-of-seeping-decay",
  "standard of slaughter": "magic-item/standard-of-slaughter",
  "standard of the cursing word": "magic-item/standard-of-the-cursing-word",
  "stone of spite": "magic-item/stone-of-spite",
  "storm banner": "magic-item/storm-banner",
  "storm daemon": "magic-item/storm-daemon",
  "stream of contagion": "magic-item/stream-of-contagion",
  "strollaz' rune": "magic-item/strollaz-rune",
  "sun standard of chotec": "magic-item/sun-standard-of-chotec",
  "supernatural horror": "magic-item/supernatural-horror",
  "sword of battle": "magic-item/sword-of-battle",
  "sword of heroes": "magic-item/sword-of-heroes",
  "sword of justice": "magic-item/sword-of-justice",
  "sword of kings": "magic-item/sword-of-kings",
  "sword of might": "magic-item/sword-of-might",
  "sword of ruin": "magic-item/sword-of-ruin",
  "sword of striking": "magic-item/sword-of-striking",
  "sword of swiftness": "magic-item/sword-of-swiftness",
  "sword of the quest": "magic-item/sword-of-the-quest",
  "sword of the stout hearted": "magic-item/sword-of-the-stout-hearted",
  "tablets of tahoth": "magic-item/tablets-of-tahoth",
  "talisman of protection": "magic-item/talisman-of-protection",
  "tapestry of conquered lands": "magic-item/tapestry-of-conquered-lands",
  tenderiser: "magic-item/tenderiser",
  "the accursed armour": "magic-item/the-accursed-armour",
  "the big red raggedy flag": "magic-item/the-big-red-raggedy-flag",
  "the blackened plate": "magic-item/the-blackened-plate",
  "the blade of leaping gold": "magic-item/the-blade-of-leaping-gold",
  "the blazing banner": "magic-item/the-blazing-banner",
  "the blessed blade of ptra": "magic-item/the-blessed-blade-of-ptra",
  "the chariot of the gods": "magic-item/the-chariot-of-the-gods",
  "the cloak of beards": "magic-item/the-cloak-of-beards",
  "the collar of zorga": "magic-item/the-collar-of-zorga",
  "the conqueror's blade": "magic-item/the-conquerors-blade",
  "the crown of nehekhara": "magic-item/the-crown-of-nehekhara",
  "the dolorous blade": "magic-item/the-dolorous-blade",
  "the fellblade": "magic-item/the-fellblade",
  "the flail of conquered kings": "magic-item/the-flail-of-conquered-kings",
  "the flayed hauberk": "magic-item/the-flayed-hauberk",
  "the gleaming pennant": "magic-item/the-gleaming-pennant",
  "the graven sceptre": "magic-item/the-graven-sceptre",
  "the guiding eye": "magic-item/the-guiding-eye",
  "the lammasu's beard": "magic-item/the-lammasus-beard",
  "the loremaster's cloak": "magic-item/the-loremasters-cloak",
  "the mask of the furnace": "magic-item/the-mask-of-the-furnace",
  "the plague chalice": "magic-item/the-plague-chalice",
  "the scarab brooch of usirian": "magic-item/the-scarab-brooch-of-usirian",
  "the screaming banner": "magic-item/the-screaming-banner",
  "the seal of parravon": "magic-item/the-seal-of-parravon",
  "the silver horn": "magic-item/the-silver-horn",
  "the staff of the elements": "magic-item/the-staff-of-the-elements",
  "the white cloak": "magic-item/the-white-cloak",
  "the white sword": "magic-item/the-white-sword",
  thundermace: "magic-item/thundermace",
  "tome of furion": "magic-item/tome-of-furion",
  "totem of eternal war": "magic-item/totem-of-eternal-war",
  "totem of prophecy": "magic-item/totem-of-prophecy",
  "totem of rust": "magic-item/totem-of-rust",
  "transcendent healing": "magic-item/transcendent-healing",
  "trappings of nurgle": "magic-item/trappings-of-nurgle",
  "trollhide trousers": "magic-item/trollhide-trousers",
  "twin heads": "magic-item/twin-heads",
  "uncanny senses": "magic-item/uncanny-senses",
  "valorous standard": "magic-item/valorous-standard",
  "venom of the firefly frog": "magic-item/venom-of-the-firefly-frog",
  "vial of lammasu blood": "magic-item/vial-of-lammasu-blood",
  "virtue of audacity": "magic-item/virtue-of-audacity",
  "virtue of confidence": "magic-item/virtue-of-confidence",
  "virtue of discipline": "magic-item/virtue-of-discipline",
  "virtue of duty": "magic-item/virtue-of-duty",
  "virtue of empathy": "magic-item/virtue-of-empathy",
  "virtue of heroism": "magic-item/virtue-of-heroism",
  "virtue of knightly temper": "magic-item/virtue-of-knightly-temper",
  "virtue of noble disdain": "magic-item/virtue-of-noble-disdain",
  "virtue of purity": "magic-item/virtue-of-purity",
  "virtue of stoicism": "magic-item/virtue-of-stoicism",
  "virtue of the ideal": "magic-item/virtue-of-the-ideal",
  "virtue of the impetuous knight": "magic-item/virtue-of-the-impetuous-knight",
  "virtue of the joust": "magic-item/virtue-of-the-joust",
  "virtue of the penitent": "magic-item/virtue-of-the-penitent",
  "vitriolic totem": "magic-item/vitriolic-totem",
  "von carstein ring": "magic-item/von-carstein-ring",
  "waaagh! banner": "magic-item/waaagh-banner",
  "wailing arrow": "magic-item/wailing-arrow",
  "wand of jet": "magic-item/wand-of-jet",
  "wand of wych elm": "magic-item/wand-of-wych-elm",
  "wandering deliberations": "magic-item/wandering-deliberations",
  "war banner": "magic-item/war-banner",
  "warden of saphery": "magic-item/warden-of-saphery",
  "warding splint": "magic-item/warding-splint",
  "warp condenser": "magic-item/warp-condenser",
  "warpstone amulet": "magic-item/warpstone-amulet",
  "warpstone armour": "magic-item/warpstone-armour",
  "warpstone tokens": "magic-item/warpstone-tokens",
  "weeping blade": "magic-item/weeping-blade",
  "whip of agony": "magic-item/whip-of-agony",
  "will of tzeentch": "magic-item/will-of-tzeentch",
  "winged horror": "magic-item/winged-horror",
  "wizard's familiar": "magic-item/wizards-familiar",
  "wizard's staff": "magic-item/wizards-staff",
  "wizarding hat": "magic-item/wizarding-hat",
  "wollopa's one hit wunda": "magic-item/wollopas-one-hit-wunda",
  wraithstone: "magic-item/wraithstone",
  "wyrmbreath vial": "magic-item/wyrmbreath-vial",
};

const additionalOWBRules = {
  "throwing spears": "weapons-of-war/throwing-spear",
  halberds: "weapons-of-war/halberd",
  "additional hand weapons":
    "weapons-of-war/two-hand-weapons-additional-hand-weapon",
  "cavalry spears": "weapons-of-war/cavalry-spear",
  "repeater handguns": "weapons-of-war/repeater-handgun",
  "hand weapons": "weapons-of-war/hand-weapon",
  flails: "weapons-of-war/flail",
  "plague censers": "weapons-of-war/plague-censer",
  "great weapons": "weapons-of-war/great-weapon",
  whips: "weapons-of-war/whip",
  spears: "weapons-of-war/spears",
  "morning stars": "weapons-of-war/morning-star",
  blowpipes: "weapons-of-war/blowpipe",
  "warplock jezzails": "weapons-of-war/warplock-jezzail",
  handguns: "weapons-of-war/handgun",
  lances: "weapons-of-war/lance",
  shortbows: "weapons-of-war/shortbow",
  "thrusting spears": "weapons-of-war/thrusting-spear",
  javelins: "weapons-of-war/javelin",
  longbows: "weapons-of-war/longbow",
  pistols: "weapons-of-war/pistol",
  "throwing axes": "weapons-of-war/throwing-axe",
  warbows: "weapons-of-war/warbow",
  hellblades: "weapons-of-war/hellblade",
  "repeater pistols": "weapons-of-war/repeater-pistol",
  "blackbriar javelins": "weapons-of-war/blackbriar-javelin",
  drakeguns: "weapons-of-war/drakegun",
  "great hammers": "weapons-of-war/great-hammer",
  "brimstone guns": "weapons-of-war/brimstone-gun",
  clatterguns: "weapons-of-war/clattergun",
  "steam guns": "weapons-of-war/steam-gun-dwarfs",
  crossbows: "weapons-of-war/crossbow",
  "throwing weapons": "weapons-of-war/throwing-weapons",
  slings: "weapons-of-war/sling",
  blunderbusses: "weapons-of-war/blunderbuss",
  "repeater handbows": "weapons-of-war/repeater-handbow",
  "repeater crossbows": "weapons-of-war/repeater-crossbow",
  "daemons of khorne": "special-rules/daemon-of-khorne",
  "daemons of tzeentch": "special-rules/daemon-of-tzeentch",
  "daemons of nurgle": "special-rules/daemon-of-nurgle",
  "daemons of slaanesh": "special-rules/daemon-of-slaanesh",
  "asrai spears": "weapons-of-war/asrai-spear",
  "asrai longbows": "weapons-of-war/asrai-longbow",
  shield: "weapons-of-war/shield",
  shields: "weapons-of-war/shield",
  ironfists: "weapons-of-war/ironfist",
  general: "characters/the-general-characters",
  "moonfire shots": "weapons-of-war/moonfire-shot",
  "battle standard bearer": "characters/the-battle-standard",
  "revered guardian": "characters/the-battle-standard",
  "patrol leader": "characters/the-battle-standard",
  ancient: "characters/the-battle-standard",
  "sky leader": "characters/the-battle-standard",
  boss: "command-groups/champions",
  marksman: "command-groups/champions",
  preceptor: "command-groups/champions",
  seneschal: "command-groups/champions",
  "skeleton champion": "command-groups/champions",
  "inner circle preceptor": "command-groups/champions",
  "doom wolf": "command-groups/champions",
  "crypt haunter": "command-groups/champions",
  "crypt ghast": "command-groups/champions",
  "glade knight": "command-groups/champions",
  kastellan: "command-groups/champions",
  sharpshooter: "command-groups/champions",
  hellwraith: "command-groups/champions",
  crusher: "command-groups/champions",
  "demigryph preceptor": "command-groups/champions",
  "count's champion": "command-groups/champions",
  vargoyle: "command-groups/champions",
  "wildwood warden": "command-groups/champions",
  "first knight": "command-groups/champions",
  bladesinger: "command-groups/champions",
  "handmaiden of the thorn": "command-groups/champions",
  "hell knight": "command-groups/champions",
  plagueridden: "command-groups/champions",
  "spawn leader": "command-groups/champions",
  "iridescent horror": "command-groups/champions",
  "ectoplasmic horror": "command-groups/champions",
  heartseeker: "command-groups/champions",
  alluress: "command-groups/champions",
  "master moulder": "command-groups/champions",
  sergeant: "command-groups/champions",
  bloodreaper: "command-groups/champions",
  nymph: "command-groups/champions",
  guardian: "command-groups/champions",
  harbinger: "command-groups/champions",
  "high sister": "command-groups/champions",
  groinbiter: "command-groups/champions",
  snarefinger: "command-groups/champions",
  "high helm": "command-groups/champions",
  "maneater captain": "command-groups/champions",
  thunderfist: "command-groups/champions",
  "keeper of the flame": "command-groups/champions",
  nightleader: "command-groups/champions",
  assassin: "command-groups/champions",
  greyback: "command-groups/champions",
  "sea master": "command-groups/champions",
  "pack leader": "command-groups/champions",
  "grail guardian": "command-groups/champions",
  champion: "command-groups/champions",
  gutlord: "command-groups/champions",
  desperado: "command-groups/champions",
  "wild hunter": "command-groups/champions",
  "wind rider": "command-groups/champions",
  esquire: "command-groups/champions",
  elder: "command-groups/champions",
  "lord's bowmen": "command-groups/champions",
  "ol' deadeye": "command-groups/champions",
  "royal champion": "command-groups/champions",
  sentinel: "command-groups/champions",
  yeoman: "command-groups/champions",
  gallant: "command-groups/champions",
  pyroclaster: "command-groups/champions",
  villein: "command-groups/champions",
  paragon: "command-groups/champions",
  warden: "command-groups/champions",
  "militia leader": "command-groups/champions",
  ironbeard: "command-groups/champions",
  "ripperdactyl champion": "command-groups/champions",
  prospector: "command-groups/champions",
  "eternal warden": "command-groups/champions",
  ironwarden: "command-groups/champions",
  "prophet of doom": "command-groups/champions",
  overseer: "command-groups/champions",
  deathmask: "command-groups/champions",
  "plague deacon": "command-groups/champions",
  fangleader: "command-groups/champions",
  clawleader: "command-groups/champions",
  "standard bearer": "command-groups/standard-bearers",
  musician: "command-groups/musicians",
  bellower: "special-rules/bellowers-and-musicians",
  "level 1 wizard": "magic/levels-of-wizardry",
  "level 2 wizard": "magic/levels-of-wizardry",
  "level 3 wizard": "magic/levels-of-wizardry",
  "level 4 wizard": "magic/levels-of-wizardry",
};

export const rulesMap = {
  ...rulesIndexExport,
  ...additionalOWBRules,
};
