const rulesIndexExport = {
  "mob rule": "special-rules/mob-rule",
  "rampant mutation": "special-rules/rampant-mutation",
  "my will be done": "special-rules/my-will-be-done",
  brayhorn: "special-rules/brayhorn",
  "ancestral grudge": "special-rules/ancestral-grudge",
  "banner of the king": "special-rules/banner-of-the-king",
  "slaughterer's call": "special-rules/slaughterers-call",
  oathstone: "special-rules/oathstone",
  "big stabbas": "special-rules/big-stabbas",
  "ogre charge": "special-rules/ogre-charge",
  "sworn protector": "special-rules/sworn-protector",
  "bestial charge": "special-rules/bestial-charge",
  "borne aloft": "special-rules/borne-aloft",
  "spawn of khorne": "special-rules/spawn-of-khorne",
  "skulking menace": "special-rules/skulking-menace",
  netters: "special-rules/netters",
  "spawn of nurgle": "special-rules/spawn-of-nurgle",
  "arise!": "special-rules/arise",
  "ancestral shield": "special-rules/ancestral-shield",
  "storm call": "special-rules/storm-call",
  "from beneath the sands": "special-rules/from-beneath-the-sands",
  "spawn of slaanesh": "special-rules/spawn-of-slaanesh",
  "maddening aura": "special-rules/maddening-aura",
  "strike the runes": "special-rules/strike-the-runes",
  "release the fanatics!": "special-rules/release-the-fanatics",
  "spawn of tzeentch": "special-rules/spawn-of-tzeentch",
  "spurting bile blood": "special-rules/spurting-bile-blood",
  "squigs go wild": "special-rules/squigs-go-wild",
  "the hierophant": "special-rules/the-hierophant",
  forgefire: "special-rules/forgefire",
  handler: "special-rules/handler",
  "ker-splat": "special-rules/ker-splat",
  "slayer of daemons": "special-rules/slayer-of-daemons",
  "stony stare": "special-rules/stony-stare",
  "eternal taskmaster": "special-rules/eternal-taskmaster",
  "spiked ball & chains": "special-rules/spiked-ball-and-chains",
  ambushers: "special-rules/ambushers",
  "cloud of dust": "special-rules/cloud-of-dust",
  "wilful beast": "special-rules/wilful-beast",
  "slayer of dragons": "special-rules/slayer-of-dragons",
  ghostsight: "special-rules/ghostsight",
  "two-headed dragon": "special-rules/two-headed-dragon",
  "armour bane": "special-rules/armour-bane",
  "artillery master": "special-rules/artillery-master",
  "unstoppable assault": "special-rules/unstoppable-assault",
  "soul-eater": "special-rules/soul-eater",
  "giant attacks": "special-rules/giant-attacks",
  entrenchment: "special-rules/entrenchment",
  "soul reaper": "special-rules/soul-reaper",
  "pick up and...": "special-rules/pick-up-and",
  "armoured hide": "special-rules/armoured-hide",
  "caged fury": "special-rules/caged-fury",
  "swallow whole": "special-rules/swallow-whole",
  "screaming skulls": "special-rules/screaming-skulls",
  "hellcannon misfire table": "special-rules/hellcannon-misfire-table",
  '"stand back chief"': "special-rules/stand-back-chief",
  bully: "special-rules/bully",
  "blood greed": "special-rules/blood-greed",
  "breath weapon": "special-rules/breath-weapon",
  "blood rage": "special-rules/blood-rage",
  venerable: "special-rules/venerable",
  "chariot runners": "special-rules/chariot-runners",
  "big 'uns": "special-rules/big-uns",
  "chaos armour": "special-rules/chaos-armour-x",
  "skulls of the foe": "special-rules/skulls-of-the-foe",
  "covenant of power": "special-rules/covenant-of-power",
  "royal guard": "special-rules/royal-guard",
  "ensorcelled weapons": "special-rules/ensorcelled-weapons",
  choppas: "special-rules/choppas",
  "bull-gors": "special-rules/bull-gors",
  "close order": "special-rules/close-order",
  "gaze of the gods": "special-rules/gaze-of-the-gods",
  "da boyz": "special-rules/da-boyz",
  "immovable object": "special-rules/immovable-object",
  drunken: "special-rules/drunken",
  "counter charge": "special-rules/counter-charge",
  "stoic defenders": "special-rules/stoic-defenders",
  "fear of elves": "special-rules/fear-of-elves",
  "runes of protection": "special-rules/runes-of-protection",
  "unbound spirits": "special-rules/unbound-spirits",
  "foe render": "special-rules/foe-render",
  "marks of chaos": "special-rules/marks-of-chaos",
  cumbersome: "special-rules/cumbersome",
  "mark of chaos undivided": "special-rules/mark-of-chaos-undivided",
  "primal fury": "special-rules/primal-fury",
  detachment: "special-rules/detachment",
  "runes of warding": "special-rules/runes-of-warding",
  "vortex of souls": "special-rules/vortex-of-souls",
  "ignore goblin panic": "special-rules/ignore-goblin-panic",
  '"fight me!"': "special-rules/fight-me",
  "dragged along": "special-rules/dragged-along",
  "razor tusks": "special-rules/razor-tusks",
  "arrows of asaph": "special-rules/arrows-of-asaph",
  "mark of khorne": "special-rules/mark-of-khorne",
  "ignore panic": "special-rules/ignore-panic",
  "quell impetuosity": "special-rules/quell-impetuosity",
  "cleaving blow": "special-rules/cleaving-blow",
  drilled: "special-rules/drilled",
  "mark of nurgle": "special-rules/mark-of-nurgle",
  slayer: "special-rules/slayer",
  "the quickening storm": "special-rules/the-quickening-storm",
  "curse of the necropolis": "special-rules/curse-of-the-necropolis",
  "tusker charge": "special-rules/tusker-charge",
  "dive bomb": "special-rules/dive-bomb",
  "mark of slaanesh": "special-rules/mark-of-slaanesh",
  ethereal: "special-rules/ethereal",
  "mark of tzeentch": "special-rules/mark-of-tzeentch",
  "dry as dust": "special-rules/dry-as-dust",
  "bombing run": "special-rules/bombing-run",
  evasive: "special-rules/evasive",
  "waaagh!": "special-rules/waaagh",
  indomitable: "special-rules/indomitable-x",
  deathblow: "special-rules/deathblow",
  warpaint: "special-rules/warpaint",
  "extra attacks": "special-rules/extra-attacks",
  "fast cavalry": "special-rules/fast-cavalry",
  khopesh: "special-rules/khopesh",
  "dwarf crafted": "special-rules/dwarf-crafted",
  "gromril armour": "special-rules/gromril-armour",
  "nehekharan phalanx": "special-rules/nehekharan-phalanx",
  fear: "special-rules/fear",
  "gromril weapons": "special-rules/gromril-weapons",
  "nehekharan undead": "special-rules/nehekharan-undead",
  "feigned flight": "special-rules/feigned-flight",
  "fight in extra rank": "special-rules/fight-in-extra-rank",
  "resurrecting the fallen": "special-rules/resurrecting-the-fallen",
  resolute: "special-rules/resolute",
  "rune lore": "special-rules/rune-lore",
  "fire & flee": "special-rules/fire-and-flee",
  "first charge": "special-rules/first-charge",
  "flaming attacks": "special-rules/flaming-attacks",
  flammable: "special-rules/flammable",
  fly: "special-rules/fly",
  frenzy: "special-rules/frenzy",
  "furious charge": "special-rules/furious-charge",
  hatred: "special-rules/hatred",
  horde: "special-rules/horde",
  howdah: "special-rules/howdah",
  "ignores cover": "special-rules/ignores-cover",
  "immune to psychology": "special-rules/immune-to-psychology",
  "impact hits": "special-rules/impact-hits",
  impetuous: "special-rules/impetuous",
  "killing blow": "special-rules/killing-blow",
  "large target": "special-rules/large-target",
  levies: "special-rules/levies",
  loner: "special-rules/loner",
  "magical attacks": "special-rules/magical-attacks",
  "magic resistance": "special-rules/magic-resistance",
  mercenaries: "special-rules/mercenaries",
  "monster handlers": "special-rules/monster-handlers",
  "monster slayer": "special-rules/monster-slayer",
  "motley crew": "special-rules/motley-crew",
  "move & shoot": "special-rules/move-and-shoot",
  "move or shoot": "special-rules/move-or-shoot",
  "move through cover": "special-rules/move-through-cover",
  "multiple shots": "special-rules/multiple-shots",
  "multiple wounds": "special-rules/multiple-wounds",
  "open order": "special-rules/open-order",
  "poisoned attacks": "special-rules/poisoned-attacks",
  ponderous: "special-rules/ponderous",
  "quick shot": "special-rules/quick-shot",
  "rallying cry": "special-rules/rallying-cry",
  "random attacks": "special-rules/random-attacks",
  "random movement": "special-rules/random-movement",
  regeneration: "special-rules/regeneration",
  "regimental unit": "special-rules/regimental-unit",
  "requires two hands": "special-rules/requires-two-hands",
  "reserve move": "special-rules/reserve-move",
  scouts: "special-rules/scouts",
  shieldwall: "special-rules/shieldwall",
  skirmishers: "special-rules/skirmishers",
  "stomp attacks": "special-rules/stomp-attacks",
  "strike first": "special-rules/strike-first",
  "strike last": "special-rules/strike-last",
  stubborn: "special-rules/stubborn",
  stupidity: "special-rules/stupidity",
  swiftstride: "special-rules/swiftstride",
  terror: "special-rules/terror",
  "timmm-berrr!": "special-rules/timmm-berrr",
  unbreakable: "special-rules/unbreakable",
  unstable: "special-rules/unstable",
  vanguard: "special-rules/vanguard",
  veteran: "special-rules/veteran",
  "volley fire": "special-rules/volley-fire",
  warband: "special-rules/warband",
  "warp-spawned": "special-rules/warp-spawned",
  "fanatic ball & chain": "weapons-of-war/fanatic-ball-and-chain",
  "ritual blade": "weapons-of-war/ritual-blade",
  braystaff: "weapons-of-war/braystaff",
  "great hammer": "weapons-of-war/great-hammer",
  "dark fire of chaos": "weapons-of-war/dark-fire-of-chaos",
  "brace of drakefire pistols": "weapons-of-war/brace-of-drakefire-pistols",
  "slythey tongue": "weapons-of-war/slythey-tongue",
  "huge gob": "weapons-of-war/huge-gob",
  greatbow: "weapons-of-war/greatbow",
  "fumes of contagion": "weapons-of-war/fumes-of-contagion",
  "flaming breath": "weapons-of-war/flaming-breath",
  "writhing tail": "weapons-of-war/writhing-tail",
  "petrifying gaze": "weapons-of-war/petrifying-gaze",
  "troll vomit": "weapons-of-war/troll-vomit",
  drakegun: "weapons-of-war/drakegun",
  "breath of desiccation": "weapons-of-war/breath-of-desiccation",
  "hand weapon": "weapons-of-war/hand-weapon",
  "cinderblast bombs": "weapons-of-war/cinderblast-bombs",
  "fiend tail": "weapons-of-war/fiend-tail",
  "acidic vomit": "weapons-of-war/acidic-vomit",
  "wicked claws": "weapons-of-war/wicked-claws",
  "trollhammer torpedo": "weapons-of-war/trollhammer-torpedo",
  "envenomed sting": "weapons-of-war/envenomed-sting",
  "hurl attack": "weapons-of-war/hurl-attack",
  doomfire: "weapons-of-war/doomfire",
  "venomous tail": "weapons-of-war/venomous-tail",
  "two hand weapons": "weapons-of-war/two-hand-weapons-additional-hand-weapon",
  "additional hand weapon":
    "weapons-of-war/two-hand-weapons-additional-hand-weapon",
  "blasting charges": "weapons-of-war/blasting-charges",
  flail: "weapons-of-war/flail",
  "fiery roar": "weapons-of-war/fiery-roar",
  "venom surge": "weapons-of-war/venom-surge",
  "cleaver-limbs": "weapons-of-war/cleaver-limbs",
  "great weapon": "weapons-of-war/great-weapon",
  "decapitating claws": "weapons-of-war/decapitating-claws",
  "steam drill": "weapons-of-war/steam-drill",
  "spidersilk lobber": "weapons-of-war/spidersilk-lobber",
  halberd: "weapons-of-war/halberd",
  "paired great khopeshes": "weapons-of-war/paired-great-khopeshes",
  "colossal fang-filled gob": "weapons-of-war/colossal-fang-filled-gob",
  "steam gun": "weapons-of-war/steam-gun",
  "giant's club": "weapons-of-war/giants-club",
  "doom diver": "weapons-of-war/doom-diver",
  "brimstone gun": "weapons-of-war/brimstone-gun",
  "morning star": "weapons-of-war/morning-star",
  "cleaing blades": "weapons-of-war/cleaing-blades",
  whip: "weapons-of-war/whip",
  "decapitating strike": "weapons-of-war/decapitating-strike",
  clattergun: "weapons-of-war/clattergun",
  "screaming skull catapult": "weapons-of-war/screaming-skull-catapult",
  lance: "weapons-of-war/lance",
  "cavalry spear": "weapons-of-war/cavalry-spear",
  "throwing spear": "weapons-of-war/throwing-spear",
  "thrusting spear": "weapons-of-war/thrusting-spear",
  longbow: "weapons-of-war/longbow",
  shortbow: "weapons-of-war/shortbow",
  warbow: "weapons-of-war/warbow",
  handgun: "weapons-of-war/handgun",
  pistol: "weapons-of-war/pistol",
  "brace of pistols": "weapons-of-war/brace-of-pistols",
  "repeater handgun": "weapons-of-war/repeater-handgun",
  "repeater pistol": "weapons-of-war/repeater-pistol",
  crossbow: "weapons-of-war/crossbow",
  "repeater crossbow": "weapons-of-war/repeater-crossbow",
  "repeater handbow": "weapons-of-war/repeater-handbow",
  "brace of repeater handbows": "weapons-of-war/brace-of-repeater-handbows",
  "throwing weapons": "weapons-of-war/throwing-weapons",
  javelin: "weapons-of-war/javelin",
  sling: "weapons-of-war/sling",
  "throwing axe": "weapons-of-war/throwing-axe",
  "light armour": "weapons-of-war/light-armour",
  "heavy armour": "weapons-of-war/heavy-armour",
  "full plate armour": "weapons-of-war/full-plate-armour",
  "lore of nehekhara": "the-lores-of-magic/lore-of-nehekhara",
  "lore of chaos": "the-lores-of-magic/lore-of-chaos",
  "lore of gork": "the-lores-of-magic/lore-of-gork",
  "lore of beasts": "the-lores-of-magic/lore-of-beasts",
  "lore of mork": "the-lores-of-magic/lore-of-mork",
  "battle magic": "the-lores-of-magic/battle-magic",
  daemonology: "the-lores-of-magic/daemonology",
  "dark magic": "the-lores-of-magic/dark-magic",
  elementalism: "the-lores-of-magic/elementalism",
  "high magic": "the-lores-of-magic/high-magic",
  illusion: "the-lores-of-magic/illusion",
  necromancy: "the-lores-of-magic/necromancy",
  "waaagh! magic": "the-lores-of-magic/waaagh-magic",
  "'eadbuttin' 'at": "magic-item/eadbuttin-at",
  "acid ichor": "magic-item/acid-ichor",
  "arcane familiar": "magic-item/arcane-familiar",
  "armour of destiny": "magic-item/armour-of-destiny",
  "armour of meteoric iron": "magic-item/armour-of-meteoric-iron",
  "armour of mork": "magic-item/armour-of-mork",
  "armour of silvered steel": "magic-item/armour-of-silvered-steel",
  "armour of the ages": "magic-item/armour-of-the-ages",
  "armour of the damned": "magic-item/armour-of-the-damned",
  "aura of pain": "magic-item/aura-of-pain",
  "axe of men": "magic-item/axe-of-men",
  "banner of iron resolve": "magic-item/banner-of-iron-resolve",
  "banner of outrage": "magic-item/banner-of-outrage",
  "banner of rage": "magic-item/banner-of-rage",
  "banner of the gods": "magic-item/banner-of-the-gods",
  "battleaxe of the last big waaagh!":
    "magic-item/battleaxe-of-the-last-big-waaagh",
  "bedazzling helm": "magic-item/bedazzling-helm",
  "berserker blade": "magic-item/berserker-blade",
  "big boss 'at": "magic-item/big-boss-at",
  "biting blade": "magic-item/biting-blade",
  "blasted standard": "magic-item/blasted-standard",
  "brazen collar": "magic-item/brazen-collar",
  "burning blade": "magic-item/burning-blade",
  "buzgob's knobbly staff": "magic-item/buzgobs-knobbly-staff",
  "chaos runesword": "magic-item/chaos-runesword",
  "charmed shield": "magic-item/charmed-shield",
  "cloak of the dunes": "magic-item/cloak-of-the-dunes",
  "collar of shapesh": "magic-item/collar-of-shapesh",
  "crimson armour of dargan": "magic-item/crimson-armour-of-dargan",
  "crook & flail of radiance": "magic-item/crook-and-flail-of-radiance",
  "crown of everlasting conquest": "magic-item/crown-of-everlasting-conquest",
  "crown of horns": "magic-item/crown-of-horns",
  "crown of kings": "magic-item/crown-of-kings",
  "da banner of butchery": "magic-item/da-banner-of-butchery",
  "da choppiest choppa": "magic-item/da-choppiest-choppa",
  "daemon-flesh": "magic-item/daemon-flesh",
  daemonsword: "magic-item/daemonsword",
  "dark heart": "magic-item/dark-heart",
  "dark majesty": "magic-item/dark-majesty",
  dawnstone: "magic-item/dawnstone",
  "death mask of kharnutt": "magic-item/death-mask-of-kharnutt",
  "destroyer of eternities": "magic-item/destroyer-of-eternities",
  "diabolic splendour": "magic-item/diabolic-splendour",
  "dispel scroll": "magic-item/dispel-scroll",
  "doom totem": "magic-item/doom-totem",
  "dragon slaying sword": "magic-item/dragon-slaying-sword",
  "duellist's blades": "magic-item/duellists-blades",
  "earthing rod": "magic-item/earthing-rod",
  "enchanted shield": "magic-item/enchanted-shield",
  "enchanting aura": "magic-item/enchanting-aura",
  "enkhil's kanopi": "magic-item/enkhils-kanopi",
  "extra arm": "magic-item/extra-arm",
  "favour of the gods": "magic-item/favour-of-the-gods",
  "feedback scroll": "magic-item/feedback-scroll",
  "filth mace": "magic-item/filth-mace",
  "flail of skulls": "magic-item/flail-of-skulls",
  "flying carpet": "magic-item/flying-carpet",
  "fungus wine": "magic-item/fungus-wine",
  "giant blade": "magic-item/giant-blade",
  "glittering scales": "magic-item/glittering-scales",
  "glittering wotnots": "magic-item/glittering-wotnots",
  "glowy green amulet": "magic-item/glowy-green-amulet",
  "gnarled hide": "magic-item/gnarled-hide",
  "gouge-tusks": "magic-item/gouge-tusks",
  "grudge rune": "magic-item/grudge-rune",
  "guff's windy banner": "magic-item/guffs-windy-banner",
  "hagtree fetish": "magic-item/hagtree-fetish",
  "headsman's axe": "magic-item/headsmans-axe",
  "healing potion": "magic-item/healing-potion",
  "helm of many eyes": "magic-item/helm-of-many-eyes",
  "hieratic jar": "magic-item/hieratic-jar",
  "horn of the first beast": "magic-item/horn-of-the-first-beast",
  "hunter's spear": "magic-item/hunters-spear",
  "icon of rakaph": "magic-item/icon-of-rakaph",
  "icon of rulership": "magic-item/icon-of-rulership",
  "icon of the sacred eye": "magic-item/icon-of-the-sacred-eye",
  "idol of mork": "magic-item/idol-of-mork",
  "infernal puppet": "magic-item/infernal-puppet",
  "jagged dagger": "magic-item/jagged-dagger",
  "lore familiar": "magic-item/lore-familiar",
  luckstone: "magic-item/luckstone",
  "manbane standard": "magic-item/manbane-standard",
  mangelder: "magic-item/mangelder",
  "many-limbed fiend": "magic-item/many-limbed-fiend",
  "master of mortals": "magic-item/master-of-mortals",
  "master rune of adamant": "magic-item/master-rune-of-adamant",
  "master rune of alaric the mad": "magic-item/master-rune-of-alaric-the-mad",
  "master rune of balance": "magic-item/master-rune-of-balance",
  "master rune of breaking": "magic-item/master-rune-of-breaking",
  "master rune of calm": "magic-item/master-rune-of-calm",
  "master rune of disguise": "magic-item/master-rune-of-disguise",
  "master rune of dragon slaying": "magic-item/master-rune-of-dragon-slaying",
  "master rune of flight": "magic-item/master-rune-of-flight",
  "master rune of gromril": "magic-item/master-rune-of-gromril",
  "master rune of grungni": "magic-item/master-rune-of-grungni",
  "master rune of hesitation": "magic-item/master-rune-of-hesitation",
  "master rune of immolation": "magic-item/master-rune-of-immolation",
  "master rune of skalf blackhammer":
    "magic-item/master-rune-of-skalf-blackhammer",
  "master rune of smiting": "magic-item/master-rune-of-smiting",
  "master rune of spite": "magic-item/master-rune-of-spite",
  "master rune of stromni redbeard":
    "magic-item/master-rune-of-stromni-redbeard",
  "master rune of swiftness": "magic-item/master-rune-of-swiftness",
  "mirage banner": "magic-item/mirage-banner",
  "muscular monstrosity": "magic-item/muscular-monstrosity",
  "obsidian lodestone": "magic-item/obsidian-lodestone",
  "ogre blade": "magic-item/ogre-blade",
  "paymaster's coin": "magic-item/paymasters-coin",
  "pelt of midnight": "magic-item/pelt-of-midnight",
  "pelt of the dark young": "magic-item/pelt-of-the-dark-young",
  "pendant of damnation": "magic-item/pendant-of-damnation",
  "poisonous slime": "magic-item/poisonous-slime",
  "porko's pigstikka": "magic-item/porkos-pigstikka",
  "potion of foolhardiness": "magic-item/potion-of-foolhardiness",
  "potion of speed": "magic-item/potion-of-speed",
  "potion of strength": "magic-item/potion-of-strength",
  "potion of toughness": "magic-item/potion-of-toughness",
  "power scroll": "magic-item/power-scroll",
  "primeval club": "magic-item/primeval-club",
  "rampaging banner": "magic-item/rampaging-banner",
  "razor standard": "magic-item/razor-standard",
  "ruby ring of ruin": "magic-item/ruby-ring-of-ruin",
  "rune of banishment": "magic-item/rune-of-banishment",
  "rune of battle": "magic-item/rune-of-battle",
  "rune of burning": "magic-item/rune-of-burning",
  "rune of cleaving": "magic-item/rune-of-cleaving",
  "rune of confusion": "magic-item/rune-of-confusion",
  "rune of courage": "magic-item/rune-of-courage",
  "rune of fear": "magic-item/rune-of-fear",
  "rune of fire": "magic-item/rune-of-fire",
  "rune of forging": "magic-item/rune-of-forging",
  "rune of fortitude": "magic-item/rune-of-fortitude",
  "rune of fury": "magic-item/rune-of-fury",
  "rune of iron": "magic-item/rune-of-iron",
  "rune of luck": "magic-item/rune-of-luck",
  "rune of might": "magic-item/rune-of-might",
  "rune of parrying": "magic-item/rune-of-parrying",
  "rune of passage": "magic-item/rune-of-passage",
  "rune of preservation": "magic-item/rune-of-preservation",
  "rune of reloading": "magic-item/rune-of-reloading",
  "rune of shielding": "magic-item/rune-of-shielding",
  "rune of skewering": "magic-item/rune-of-skewering",
  "rune of speed": "magic-item/rune-of-speed",
  "rune of spellbreaking": "magic-item/rune-of-spellbreaking",
  "rune of stone": "magic-item/rune-of-stone",
  "rune of striking": "magic-item/rune-of-striking",
  "rune of the beast ascendant": "magic-item/rune-of-the-beast-ascendant",
  "rune of the furnace": "magic-item/rune-of-the-furnace",
  "rune of the true beast": "magic-item/rune-of-the-true-beast",
  "rune of warding": "magic-item/rune-of-warding",
  "scarab brooch": "magic-item/scarab-brooch",
  "scroll of transmogrification": "magic-item/scroll-of-transmogrification",
  "serpent staff": "magic-item/serpent-staff",
  "shield of ptra": "magic-item/shield-of-ptra",
  "shield of the warrior true": "magic-item/shield-of-the-warrior-true",
  "skin of man": "magic-item/skin-of-man",
  "skull of katam": "magic-item/skull-of-katam",
  "slug-skin": "magic-item/slug-skin",
  "spell familiar": "magic-item/spell-familiar",
  "spelleater axe": "magic-item/spelleater-axe",
  spellshield: "magic-item/spellshield",
  "spellthieving sword": "magic-item/spellthieving-sword",
  "stalwart rune": "magic-item/stalwart-rune",
  "standard of the cursing word": "magic-item/standard-of-the-cursing-word",
  "stone of spite": "magic-item/stone-of-spite",
  "strollaz' rune": "magic-item/strollaz-rune",
  "sword of battle": "magic-item/sword-of-battle",
  "sword of might": "magic-item/sword-of-might",
  "sword of striking": "magic-item/sword-of-striking",
  "sword of swiftness": "magic-item/sword-of-swiftness",
  "talisman of protection": "magic-item/talisman-of-protection",
  "the big red raggedy flag": "magic-item/the-big-red-raggedy-flag",
  "the blackened plate": "magic-item/the-blackened-plate",
  "the blazing banner": "magic-item/the-blazing-banner",
  "the collar of zorga": "magic-item/the-collar-of-zorga",
  "the plague chalice": "magic-item/the-plague-chalice",
  "totem of rust": "magic-item/totem-of-rust",
  "trollhide trousers": "magic-item/trollhide-trousers",
  "uncanny senses": "magic-item/uncanny-senses",
  "vitriolic totem": "magic-item/vitriolic-totem",
  "waaagh! banner": "magic-item/waaagh-banner",
  "wand of jet": "magic-item/wand-of-jet",
  "war banner": "magic-item/war-banner",
  "wizarding hat": "magic-item/wizarding-hat",
  "wollopa's one hit wunda": "magic-item/wollopas-one-hit-wunda",
};

const additionalOWBRules = {
  "throwing spears": "weapons-of-war/throwing-spear",
  halberds: "weapons-of-war/halberd",
  "additional hand weapons":
    "weapons-of-war/two-hand-weapons-additional-hand-weapon",
  "cavalry spears": "weapons-of-war/cavalry-spear",
  "repeater handguns": "weapons-of-war/repeater-handgun",
  "hand weapons": "weapons-of-war/hand-weapon",
  flails: "weapons-of-war/flail",
  "great weapons": "weapons-of-war/great-weapon",
  whips: "weapons-of-war/whip",
  spears: "weapons-of-war/spears",
  "morning stars": "weapons-of-war/morning-star",
  handguns: "weapons-of-war/handgun",
  lances: "weapons-of-war/lance",
  shortbows: "weapons-of-war/shortbow",
  "thrusting spears": "weapons-of-war/thrusting-spear",
  javelins: "weapons-of-war/javelin",
  longbows: "weapons-of-war/longbow",
  pistols: "weapons-of-war/pistol",
  "throwing axes": "weapons-of-war/throwing-axe",
  warbows: "weapons-of-war/warbow",
  "repeater pistols": "weapons-of-war/repeater-pistol",
  drakeguns: "weapons-of-war/drakegun",
  "great hammers": "weapons-of-war/great-hammer",
  "brimstone guns": "weapons-of-war/brimstone-gun",
  clatterguns: "weapons-of-war/clattergun",
  "steam guns": "weapons-of-war/steam-gun",
  crossbows: "weapons-of-war/crossbow",
  "throwing weapons": "weapons-of-war/throwing-weapons",
  slings: "weapons-of-war/sling",
  "repeater handbows": "weapons-of-war/repeater-handbow",
  "repeater crossbows": "weapons-of-war/repeater-crossbow",
  shield: "weapons-of-war/shield",
  shields: "weapons-of-war/shield",
  general: "characters/the-general-characters",
  "battle standard bearer": "characters/the-battle-standard",
  boss: "command-groups/champions",
  marksman: "command-groups/champions",
  preceptor: "command-groups/champions",
  "inner circle preceptor": "command-groups/champions",
  "demigryph preceptor": "command-groups/champions",
  "count's champion": "command-groups/champions",
  sergeant: "command-groups/champions",
  elder: "command-groups/champions",
  "ol' deadeye": "command-groups/champions",
  "royal champion": "command-groups/champions",
  "militia leader": "command-groups/champions",
  ironbeard: "command-groups/champions",
  prospector: "command-groups/champions",
  ironwarden: "command-groups/champions",
  "prophet of doom": "command-groups/champions",
  overseer: "command-groups/champions",
  deathmask: "command-groups/champions",
  fangleader: "command-groups/champions",
  clawleader: "command-groups/champions",
  "standard bearer": "command-groups/standard-bearers",
  musician: "command-groups/musicians",
  "level 1 wizard": "magic/levels-of-wizardry",
  "level 2 wizard": "magic/levels-of-wizardry",
  "level 3 wizard": "magic/levels-of-wizardry",
  "level 4 wizard": "magic/levels-of-wizardry",
};

export const rulesMap = {
  ...rulesIndexExport,
  ...additionalOWBRules,
};
