import rulesIndexExport from "./rules-index-export.json";

const additionalOWBRules = {
  "throwing spears": { url: "weapons/throwing-spear" },
  halberds: { url: "weapons/halberd" },
  "additional hand weapons": {
    url: "weapons/two-hand-weapons-additional-hand-weapon",
  },
  "cavalry spears": { url: "weapons/cavalry-spear" },
  "repeater handguns": { url: "weapons/repeater-handgun" },
  "hand weapons": { url: "weapons/hand-weapon" },
  flails: { url: "weapons/flail" },
  "plague censers": { url: "weapons/plague-censer" },
  "great weapons": { url: "weapons/great-weapon" },
  whips: { url: "weapons/whip" },
  spears: { url: "weapons/spears" },
  "morning stars": { url: "weapons/morning-star" },
  blowpipes: { url: "weapons/blowpipe" },
  handguns: { url: "weapons/handgun" },
  lances: { url: "weapons/lance" },
  shortbows: { url: "weapons/shortbow" },
  "thrusting spears": { url: "weapons/thrusting-spear" },
  javelins: { url: "weapons/javelin" },
  longbows: { url: "weapons/longbow" },
  pistols: { url: "weapons/pistol" },
  "throwing axes": { url: "weapons/throwing-axe" },
  hellblades: { url: "weapons/hellblade" },
  "repeater pistols": { url: "weapons/repeater-pistol" },
  "blackbriar javelins": { url: "weapons/blackbriar-javelin" },
  drakeguns: { url: "weapons/drakegun" },
  "great hammers": { url: "weapons/great-hammer" },
  "brimstone guns": { url: "weapons/brimstone-gun" },
  clatterguns: { url: "weapons/clattergun" },
  crossbows: { url: "weapons/crossbow" },
  "throwing weapons": { url: "weapons/throwing-weapons" },
  slings: { url: "weapons/sling" },
  blunderbusses: { url: "weapons/blunderbuss" },
  "repeater handbows": { url: "weapons/repeater-handbow" },
  "repeater crossbows": { url: "weapons/repeater-crossbow" },
  "daemons of khorne": { url: "special-rules/daemon-of-khorne" },
  "daemons of tzeentch": { url: "special-rules/daemon-of-tzeentch" },
  "daemons of nurgle": { url: "special-rules/daemon-of-nurgle" },
  "daemons of slaanesh": { url: "special-rules/daemon-of-slaanesh" },
  "asrai spears": { url: "weapons/asrai-spear" },
  "asrai longbows": { url: "weapons/asrai-longbow" },
  general: { url: "characters/the-general-characters" },
  "moonfire shots": { url: "weapons/moonfire-shot" },
  "battle standard bearer": { url: "characters/the-battle-standard" },
  champions: { url: "units/banners-musicians-and-champions" },
  musician: { url: "units/banners-musicians-and-champions" },
  "standard bearer": { url: "units/banners-musicians-and-champions" },
  wizard: { url: "magic/wizards-magic" },
  "level 1 wizard": { url: "magic/wizard-levels" },
  "level 2 wizard": { url: "magic/wizard-levels" },
  "level 3 wizard": { url: "magic/wizard-levels" },
  "level 4 wizard": { url: "magic/wizard-levels" },
  "storm call warriors": {
    url: "special-rules/storm-call",
  },
  "doomseeker dwarfs": {
    url: "special-rules/doomseeker",
  },
  "armour piercing": {
    url: "the-shooting-phase/armour-piercing",
  },
  "nuln state troops empire": {
    url: "special-rules/nuln-state-troops",
  },
  "crown of horns beastmen": {
    url: "magic-item/crown-of-horns-beastmen",
  },
  "crown of horns cathay": {
    url: "weapons/crown-of-horns-grand-cathay",
  },
  "engine of the gods renegade": {
    url: "special-rules/engine-of-the-gods-renegade",
  },
  "crown of antlers beastmen": {
    url: "special-rules/crown-of-antlers",
  },
  "crown of antlers wood-elf-realms": {
    url: "magic-item/crown-of-antlers",
  },
  "heavy infantry": { url: "troop-types-in-detail/heavy-infantry" },
  "helblaster volley gun weapon": {
    url: "weapons/helblaster-volley-gun",
  },
  "helstorm rocket battery weapon": {
    url: "weapons/helstorm-rocket-battery",
  },
  "organ gun weapon": {
    url: "war-machines/organ-guns",
  },
  "screaming skull catapult weapon": {
    url: "weapons/screaming-skull-catapult",
  },
  "open-war": {
    url: "matched-play/open-war",
  },
  "grand-melee": {
    url: "matched-play/grand-melee",
  },
  "combined-arms": {
    url: "matched-play/combined-arms",
  },
  "grand-melee-combined-arms": {
    url: "warhammer-armies/army-composition-lists",
  },
  "battle-march": {
    url: "warhammer-armies/battle-march",
  },
  "dreadquake mortar weapon": {
    url: "weapons/dreadquake-mortar",
  },
};

export const synonyms = {
  "the witch": "suffer not...",
  "the revenant": "suffer not...",
  "the mutant": "suffer not...",
  "the daemon": "suffer not...",
  "spear of kurnous": "the spear of kurnous",
  warbows: "warbow",
  greatbows: "greatbow",
  "chracian great blades": "chracian great blade",
  "swords of hoeth": "sword of hoeth",
  "gromril great axes": "gromril great axe",
  "bows of avelorn": "bow of avelorn",
  "ceremonial halberds": "ceremonial halberd",
  "wolf hammers": "wolf hammer",
  shields: "shield",
  bellower: "bellowers & musicians",
  "revered guardian": "champions",
  "patrol leader": "champions",
  "sky leader": "champions",
  "great cannon": "cannon",
  "repeater bolt thrower": "bolt thrower",
  "bolt thrower": "bolt throwers",
  plagueswords: "plaguesword",
  "steam guns dwarfs": "steam gun dwarfs",
  "har ganeth greatswords": "har ganeth greatsword",
  "dread halberds": "dread halberd",
  fanatics: "fanatic",
  "nasty skulkers": "nasty skulker",
  "leadbelcher guns": "leadbelcher gun",
  "leadbelcher guns renegade": "leadbelcher gun renegade",
  "grimfrost weapons": "grimfrost weapon",
  "tiranoc chariots": "tiranoc chariot",
  "steam tank": "empire steam tank",
  halberds: "halberd",
  polearms: "polearm",
  gyrocopters: "gyrocopter",
  "scout gyrocopters": "scout gyrocopter",
  ironfists: "ironfist",
  "ironfists renegade": "ironfist renegade",
  "marauder chieftain": "champions",
  "marauder horsemaster": "champions",
  "lion guard captain": "champions",
  "chracian captain": "champions",
  "jade officer": "champions",
  "jade lancer officer": "champions",
  boss: "champions",
  marksman: "champions",
  preceptor: "champions",
  seneschal: "champions",
  "skeleton champion": "champions",
  "inner circle preceptor": "champions",
  "doom wolf": "champions",
  "crypt haunter": "champions",
  "crypt ghast": "champions",
  "glade knight": "champions",
  kastellan: "champions",
  sharpshooter: "champions",
  hellwraith: "champions",
  crusher: "champions",
  "demigryph preceptor": "champions",
  "count's champion": "champions",
  vargoyle: "champions",
  lordling: "champions",
  reaver: "champions",
  hag: "champions",
  master: "champions",
  bloodshade: "champions",
  "tower master": "champions",
  "draich master": "champions",
  "wildwood warden": "champions",
  "first knight": "champions",
  "dread knight": "champions",
  bladesinger: "champions",
  "handmaiden of the thorn": "champions",
  "hell knight": "champions",
  plagueridden: "champions",
  "spawn leader": "champions",
  "iridescent horror": "champions",
  "ectoplasmic horror": "champions",
  heartseeker: "champions",
  alluress: "champions",
  "master moulder": "champions",
  sergeant: "champions",
  "veteran sergeant": "champions",
  bloodreaper: "champions",
  nymph: "champions",
  guardian: "champions",
  harbinger: "champions",
  "high sister": "champions",
  groinbiter: "champions",
  snarefinger: "champions",
  "high helm": "champions",
  bloodkine: "champions",
  "gouge-horn": "champions",
  "true-horn": "champions",
  "half-horn": "champions",
  gorehoof: "champions",
  shartak: "champions",
  "maneater captain": "champions",
  thunderfist: "champions",
  "keeper of the flame": "champions",
  nightleader: "champions",
  assassin: "champions",
  greyback: "champions",
  "sea master": "champions",
  "pack leader": "champions",
  "grail guardian": "champions",
  champion: "champions",
  gutlord: "champions",
  desperado: "champions",
  "wild hunter": "champions",
  "wind rider": "champions",
  esquire: "champions",
  elder: "champions",
  "lord's bowmen": "champions",
  "ol' deadeye": "champions",
  "royal champion": "champions",
  sentinel: "champions",
  yeoman: "champions",
  gallant: "champions",
  pyroclaster: "champions",
  villein: "champions",
  paragon: "champions",
  warden: "champions",
  "militia leader": "champions",
  ironbeard: "champions",
  "ripperdactyl champion": "champions",
  prospector: "champions",
  "eternal warden": "champions",
  ironwarden: "champions",
  "prophet of doom": "champions",
  overseer: "champions",
  deathmask: "champions",
  "plague deacon": "champions",
  fangleader: "champions",
  watchmaster: "champions",
  "foe-render": "champions",
  "splice-horn": "champions",
  clawleader: "champions",
  "master of arms": "champions",
  "master of arrows": "champions",
  "tomb captain": "champions",
  "master charioteer": "champions",
  "master of horse": "champions",
  kroxigors: "kroxigor",
  ancient: "champions",
  "venerable ancient": "champions",
  "necropolis captain": "champions",
  "royal clan veteran": "champions",
  "borri forkbeard": "champions",
  headtaker: "champions",
  "skin wolf jarl": "champions",
  "first sword": "champions",
  captain: "champions",
  officer: "champions",
  "veteran officer": "champions",
  commander: "champions",
  "shrine keeper": "champions",
  "veteran commander": "champions",
  "boar chariot": "orc boar chariot",
  "wolf chariot": "goblin wolf chariot",
  fireglaives: "fireglaive",
  "warplock jezzails": "warplock jezzails",
  "warplock jezzails skaven": "warplock jezzail",
  "scourgerunner chariots": "scourgerunner chariot",
  "bloodwrack shrines": "bloodwrack shrine",
  "bloodwrack medusas": "bloodwrack medusa",
  "snotling pump wagons": "snotling pump wagon",
  "goblin wolf chariots": "goblin wolf chariot",
  "expeditionary marksman": "expeditionary marksmen",
  "braces of pistols": "brace of pistols",
  "troll magic": "lore of troll magic",
  "empire knights panther": "empire knights",
  "empire knights of the white wolf": "empire knights",
  "empire knights of the fiery heart": "empire knights",
  "empire knights of the blazing sun": "empire knights",
  "empire knights of morr": "empire knights",
  "inner circle knights panther": "inner circle knights",
  "inner circle knights of the white wolf": "inner circle knights",
  "inner circle knights of the fiery heart": "inner circle knights",
  "inner circle knights of the blazing sun": "inner circle knights",
  "inner circle knights of morr": "inner circle knights",
  "demigryph knights panther": "demigryph knights",
  "demigryph knights of the white wolf": "demigryph knights",
  "demigryph knights of the fiery heart": "demigryph knights",
  "demigryph knights of the blazing sun": "demigryph knights",
  "demigryph knights of morr": "demigryph knights",
  "ogre pistols": "ogre pistol",
  "light cannons": "light cannon",
  "bigger choppier axe": "bigger, choppier axe",
  orion: "orion, the king in the woods",
  araloth: "araloth, lord of talsyn",
  kralmaw: "kralmaw, the prophet of ruin",
  ghorros: "ghorros warhoof",
  "primal magic": "lore of primal magic",
  "a tingle in the air": "herdstones",
  "dark sorcery": "herdstones",
  "fearsome edifice": "herdstones",
  "bestial fury beastmen": "herdstones",
  "cathayan lances": "cathayan lance",
  "sky lantern crane guns": "sky lantern crane gun",
  "iron hail guns": "iron hail gun",
  warhorses: "warhorse",
  "barded warhorses": "barded warhorse",
  "chaos furies of tzeentch": "chaos furies",
  "chaos furies of nurgle": "chaos furies",
  "chaos furies of slaanesh": "chaos furies",
  "chaos furies of khorne": "chaos furies",
  shadowlands: "lore of the shadowlands",
};

export const rulesMap = {
  ...rulesIndexExport,
  ...additionalOWBRules,
};
